import { createCountyRegistryAction, registerCountySourceAction } from "@/app/county-actions";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { readCountyCoverage, readCountyManualReviewQueue } from "@/lib/county-source-service";
import type { CountyCoverageStatus } from "@prisma/client";

export const dynamic = "force-dynamic";
const field = "rounded-lg border px-3 py-2 text-sm";
const coverageStatuses = ["AUTOMATED","MANUAL_ONLY","RESTRICTED","PAYWALLED","TEMPORARILY_UNAVAILABLE","NOT_FOUND","NEEDS_REVIEW"] as const;
export default async function CountyCoveragePage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  await requireOwner();
  const params = await searchParams;
  const selectedStatus = coverageStatuses.includes(params.status as typeof coverageStatuses[number]) ? params.status as CountyCoverageStatus : undefined;
  const [counties, review] = await Promise.all([readCountyCoverage({ status: selectedStatus }), readCountyManualReviewQueue()]);
  return <WorkspaceShell active="county-coverage"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6">
    <header className="border-b pb-6"><p className="text-sm font-semibold text-blue-700">Official public-record coverage</p><h1 className="mt-1 text-3xl font-bold">County source registry</h1><p className="mt-2 text-sm text-slate-600">Coverage describes access, not property truth. Assessed values are dated public records—not market appraisals.</p></header>
    <form className="mt-6 flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><select className={field} defaultValue={selectedStatus ?? ""} name="status"><option value="">All coverage states</option>{coverageStatuses.map((status) => <option key={status}>{status}</option>)}</select><button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Filter coverage</button></form>
    <section className="mt-6 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-bold">Operational counties · {counties.length}</h2></div><div className="divide-y">{counties.map((county) => <article className="grid gap-3 p-5 md:grid-cols-[1fr_1fr_2fr]" key={county.id}><div><b>{county.countyName}, {county.stateCode}</b><p className="text-xs text-slate-500">FIPS {county.fipsCode}</p></div><div><b>{county.coverageStatus.replaceAll("_", " ")}</b><p className="text-xs text-slate-500">{county._count.properties} properties · {county._count.developerProjects} projects · {county._count.campaignCoverage} campaigns</p><p className="text-xs text-slate-500">Checked {county.lastAccessibilityCheckAt?.toISOString() ?? "never"}</p></div><div>{county.sources.length ? county.sources.map((source) => <p className="text-sm" key={source.id}><a className="font-bold text-blue-700 underline" href={source.officialDomain}>{source.agencyName}</a> · {source.agencyType.replaceAll("_", " ")} · {source.automationStatus.toLowerCase()} · last check {source.checks[0]?.checkedAt.toISOString() ?? "never"}</p>) : <p className="text-sm text-amber-800">No reviewed official source. Needs review.</p>}<p className="mt-1 text-xs text-slate-500">{county.coverageReason || county.failureReason || county.manualSearchInstructions || "No coverage notes."}</p></div></article>)}{!counties.length ? <p className="p-8 text-center text-slate-500">No counties match this coverage filter.</p> : null}</div></section>
    <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Manual-review queue</h2><p className="mt-1 text-sm text-slate-500">Ambiguous entity matches, conflicting or expired facts, and inaccessible counties remain unresolved.</p><div className="mt-4 grid gap-5 xl:grid-cols-3"><div><h3 className="font-bold">Entity matches · {review.entityMatches.length}</h3>{review.entityMatches.map((item) => <article className="mt-2 rounded-xl border p-3 text-sm" key={item.id}><b>{item.developer.companyName}</b><p>{item.matchedName} · {item.status.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{item.source.registry.countyName}, {item.source.registry.stateCode} · confidence {item.confidence} · observed {item.observedAt.toISOString()}</p><p className="text-xs">{item.rationale}</p></article>)}</div><div><h3 className="font-bold">County facts · {review.observations.length}</h3>{review.observations.map((item) => <article className="mt-2 rounded-xl border p-3 text-sm" key={item.id}><b>{item.fieldName} · {item.status.replaceAll("_", " ")}</b><p className="text-xs text-slate-500">{item.property?.address || item.developerProject?.address || "Unlinked record"}</p><p className="text-xs text-slate-500">{item.source.agencyName} · tax year {item.effectiveYear ?? "not supplied"} · observed {item.observedAt.toISOString()}</p><a className="text-xs font-bold text-blue-700 underline" href={item.source.officialDomain}>Open official source</a></article>)}</div><div><h3 className="font-bold">Coverage exceptions · {review.inaccessible.length}</h3>{review.inaccessible.map((item) => <article className="mt-2 rounded-xl border p-3 text-sm" key={item.id}><b>{item.countyName}, {item.stateCode}</b><p>{item.coverageStatus.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{item.failureReason || item.coverageReason || "Manual source review required."}</p></article>)}</div></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><form action={createCountyRegistryAction} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Register an operational county</h2><div className="grid grid-cols-3 gap-2"><input className={field} name="stateCode" maxLength={2} placeholder="State" required/><input className={field} name="countyName" placeholder="County" required/><input className={field} name="fipsCode" pattern="[0-9]{5}" placeholder="FIPS" required/></div><textarea className={`${field} w-full`} name="manualSearchInstructions" placeholder="Manual-search instructions"/><button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Save county</button></form>
    <form action={registerCountySourceAction} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Version an official source</h2><select className={`${field} w-full`} name="registryId" required><option value="">County</option>{counties.map((county) => <option key={county.id} value={county.id}>{county.countyName}, {county.stateCode}</option>)}</select><input className={`${field} w-full`} name="agencyName" placeholder="Agency name" required/><select className={`${field} w-full`} name="agencyType">{["ASSESSOR","APPRAISAL_DISTRICT","PROPERTY_APPRAISER","TAX","GIS","RECORDER","DEEDS","TREASURER","AUDITOR","OTHER"].map((type) => <option key={type}>{type}</option>)}</select><input className={`${field} w-full`} name="officialUrl" type="url" placeholder="Official HTTPS URL" required/><input className={`${field} w-full`} name="delegationEvidenceUrl" type="url" placeholder="Delegation evidence for vendor domains"/><input className={`${field} w-full`} name="accessMethod" placeholder="Access method" required/><select className={`${field} w-full`} name="automationStatus">{["UNKNOWN","PERMITTED","RESTRICTED","PROHIBITED"].map((status) => <option key={status}>{status}</option>)}</select><input className={`${field} w-full`} name="supportedSearches" placeholder="Supported searches, comma separated"/><input className={`${field} w-full`} name="availableFields" placeholder="Available fields, comma separated"/><input className={`${field} w-full`} name="sourceConfidence" type="number" min="0" max="100" placeholder="Confidence" required/><label className="block text-sm"><input name="authenticationRequired" type="checkbox"/> Authentication required</label><label className="block text-sm"><input name="subscriptionRequired" type="checkbox"/> Subscription required</label><button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Save source version</button></form></section>
  </div></WorkspaceShell>;
}
