import { createSellerEngagementAction, recordSellerConversationAction, recordSellerDispositionAction, scheduleSellerFollowUpAction } from "@/app/seller-crm-actions";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { getPrisma } from "@/lib/prisma";
import { readSellerCrm } from "@/lib/seller-crm";
export const dynamic = "force-dynamic"; const field = "rounded-lg border px-3 py-2 text-sm"; const channels = ["EMAIL","SMS","PHONE","MAIL","INTERNAL"];
export default async function SellerCrmPage() { await requireOwner(); const [engagements, transactions] = await Promise.all([readSellerCrm(), getPrisma().dealTransaction.findMany({ include: { property: true } })]); const options = engagements.map((item) => ({ id: item.id, label: item.transaction.property.address })); return <WorkspaceShell active="seller-crm"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6"><header className="border-b pb-6"><p className="text-sm font-semibold text-blue-700">Owner-controlled acquisition conversations</p><h1 className="mt-1 text-3xl font-bold">Seller CRM</h1><p className="mt-2 text-sm text-slate-600">Consent, suppression, policy, provider, transaction and owner gates remain mandatory.</p></header>
  <section className="mt-6 divide-y overflow-hidden rounded-2xl border bg-white">{engagements.map((item) => <article className="grid gap-3 p-5 md:grid-cols-4" key={item.id}><div><b>{item.transaction.property.address}</b><p className="text-xs text-slate-500">{item.channel} · {item.status}</p></div><div><p className="text-xs text-slate-500">Consent</p><b>{item.consents[0]?.status ?? "UNKNOWN"}</b></div><div><p className="text-xs text-slate-500">Authority</p><b>{item.sellerFacts[0]?.authorityStatus ?? "UNKNOWN"}</b></div><div><p className="text-xs text-slate-500">Next follow-up</p><b>{item.followUps[0]?.dueAt.toLocaleString() ?? "None"}</b></div><p className="text-sm md:col-span-4">{item.conversations[0]?.summary ?? "No sourced conversation recorded."}</p></article>)}{!engagements.length ? <p className="p-8 text-center text-slate-500">No seller engagement records.</p> : null}</section>
  <section className="mt-6 grid gap-6 xl:grid-cols-2"><form action={createSellerEngagementAction} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Create engagement draft</h2><select className={`${field} w-full`} name="transactionId" required><option value="">Transaction</option>{transactions.map((item) => <option key={item.id} value={item.id}>{item.property.address}</option>)}</select><select className={`${field} w-full`} name="channel">{channels.map((value) => <option key={value}>{value}</option>)}</select><input className={`${field} w-full`} name="recipient" placeholder="Recipient address or number (stored hashed)" required/><input className={`${field} w-full`} name="recipientLabel" placeholder="Recipient label"/><textarea className={`${field} w-full`} name="purpose" placeholder="Purpose" required/><button className="rounded-lg bg-slate-950 px-4 py-2 text-white">Save draft</button></form>
  <form action={recordSellerConversationAction} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Record sourced conversation</h2><select className={`${field} w-full`} name="engagementId" required><option value="">Engagement</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><input className={`${field} w-full`} name="occurredAt" type="datetime-local" required/><input className={`${field} w-full`} name="sourceType" placeholder="Call, email, meeting…" required/><input className={`${field} w-full`} name="sourceUrl" type="url" placeholder="Source URL"/><textarea className={`${field} w-full`} name="summary" placeholder="Conversation summary" required/><input className={`${field} w-full`} name="objections" placeholder="Objections"/><input className={`${field} w-full`} name="questions" placeholder="Questions"/><button className="rounded-lg bg-slate-950 px-4 py-2 text-white">Record conversation</button></form>
  <form action={scheduleSellerFollowUpAction} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Schedule follow-up</h2><select className={`${field} w-full`} name="engagementId" required><option value="">Engagement</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><input className={`${field} w-full`} name="dueAt" type="datetime-local" required/><input className={`${field} w-full`} name="reason" placeholder="Reason" required/><select className={`${field} w-full`} name="channel"><option value="">Existing channel</option>{channels.map((v) => <option key={v}>{v}</option>)}</select><button className="rounded-lg bg-slate-950 px-4 py-2 text-white">Schedule</button></form>
  <form action={recordSellerDispositionAction} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Record loss or nurture reason</h2><select className={`${field} w-full`} name="engagementId" required><option value="">Engagement</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select className={`${field} w-full`} name="reason">{["SELLER_REJECTED_PRICE","SELLER_CHOSE_ANOTHER_BUYER","SELLER_WITHDREW","UNABLE_TO_CONTACT","AUTHORITY_UNVERIFIED","SPREAD_BELOW_TARGET","COMPLIANCE_BLOCK","NURTURE","OPT_OUT","OTHER"].map((v) => <option key={v}>{v}</option>)}</select><textarea className={`${field} w-full`} name="explanation" placeholder="Explanation"/><input className={`${field} w-full`} name="nurtureUntil" type="datetime-local"/><button className="rounded-lg bg-slate-950 px-4 py-2 text-white">Record disposition</button></form></section></div></WorkspaceShell>; }
