import Link from "next/link";
import { notFound } from "next/navigation";
import { createPropertyAction } from "@/app/actions";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { readDatabase, scoreDeveloperMatches } from "@/lib/database";
import { readGovernmentResearch } from "@/lib/government-research";
import { HudReoImportForm } from "@/app/research/[fips]/hud-reo-import-form";
import { propertyReadiness } from "@/lib/domain";

export const dynamic = "force-dynamic";
const money = (value?: number | string) => value ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value)) : "Unknown";
const actionable = (status: string) => ["CONFIRMED_AVAILABLE", "GOVERNMENT_SALE"].includes(status);
function Field({ name, placeholder, type = "text", required = false }: { name: string; placeholder: string; type?: string; required?: boolean }) { return <input className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" name={name} placeholder={placeholder} required={required} type={type} />; }

export default async function MarketSourcingPage({ params }: { params: Promise<{ fips: string }> }) {
  await requireOwner();
  const { fips } = await params;
  if (!/^\d{5}$/.test(fips)) notFound();
  const [research, db] = await Promise.all([readGovernmentResearch(), readDatabase()]);
  const signal = research.signals.find((item) => item.fips === fips);
  if (!signal) notFound();
  const properties = db.properties.filter((property) => property.marketFips === fips);
  const matchCounts = new Map(await Promise.all(properties.map(async (property) => [property.id, (await scoreDeveloperMatches(property.id, false)).length] as const)));
  const ready = properties.filter((property) => propertyReadiness(property).actionable);

  return <WorkspaceShell active="research"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <Link className="text-sm font-bold text-blue-700" href="/research">← Development Radar</Link>
    <header className="mt-4 flex flex-col gap-5 border-b pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-blue-700">Market-to-Deal Bridge · FIPS {signal.fips}</p><h1 className="mt-1 text-3xl font-bold">{signal.countyName}, {signal.stateName}</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Turn this government market signal into source-backed opportunities. A permit signal is not evidence that a property is available.</p></div><a className="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold text-blue-700" href={signal.sourceUrl} rel="noreferrer" target="_blank">Open Census evidence</a></header>
    <section className="mt-6 grid gap-4 md:grid-cols-4"><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-500">Radar rank</p><p className="mt-2 text-3xl font-bold">#{signal.rank}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-500">Current units</p><p className="mt-2 text-3xl font-bold">{signal.currentUnits.toLocaleString()}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-500">Growth</p><p className="mt-2 text-3xl font-bold">{signal.growthPct === null ? "No baseline" : `${signal.growthPct >= 0 ? "+" : ""}${signal.growthPct.toFixed(1)}%`}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-500">Disposition-ready</p><p className="mt-2 text-3xl font-bold">{ready.length}</p></article></section>
    <section className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-6"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Best Action Today</p><h2 className="mt-2 text-xl font-bold">{ready.length ? "Review the strongest verified property in Disposition" : properties.length ? "Verify price and seller contact for an imported property" : "Import HUD's live public REO listings for this county"}</h2><p className="mt-2 text-sm text-slate-600">{ready.length ? "Qualified buyer matching is unlocked for the source-backed opportunities below." : properties.length ? "Open the property evidence workspace. Matching stays locked until current price, contact, and dated verification evidence are saved." : "HUD records are cross-checked against Census county geography and enter verification before matching."}</p>{ready.length ? <Link className="mt-4 inline-block rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white" href="/disposition">Open Disposition</Link> : properties.length ? <Link className="mt-4 inline-block rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white" href="/properties">Verify properties</Link> : null}<HudReoImportForm fips={signal.fips} /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_440px]"><div className="space-y-4"><div><h2 className="text-xl font-bold">County opportunity queue</h2><p className="mt-1 text-sm text-slate-500">Only records explicitly attributed to this county appear here.</p></div>{properties.map((property) => <article className="rounded-2xl border bg-white p-5 shadow-sm" key={property.id}><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${actionable(property.opportunityStatus) ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{property.opportunityStatus.replaceAll("_", " ")}</span><h3 className="mt-3 text-lg font-bold">{property.address}</h3><p className="text-sm text-slate-500">{property.city}, {property.state} {property.zipCode} · {money(property.estimatedValue)}</p></div><div className="text-sm sm:text-right"><p className="font-bold text-blue-700">{matchCounts.get(property.id) ?? 0} qualified matches</p><p className="mt-1 text-slate-500">Confidence {property.confidence}%</p></div></div><div className="mt-4 border-t pt-4 text-sm">{property.sourceUrl ? <a className="font-bold text-blue-700 underline" href={property.sourceUrl} rel="noreferrer" target="_blank">Open {property.sourceName || "official source"}</a> : <p className="font-semibold text-red-700">Official source missing</p>}<p className="mt-2 text-slate-500">Contact: {property.contactEmail || property.contactPhone || "Missing"}</p></div></article>)}{!properties.length ? <p className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">No sourced opportunities have been attributed to this county.</p> : null}</div>
      <aside className="h-fit rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Add official opportunity</h2><p className="mt-1 text-sm text-slate-500">Evidence fields are saved and audited. Records remain in verification unless availability and contact are confirmed.</p><form action={createPropertyAction} className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><input name="marketFips" type="hidden" value={signal.fips} /><Field name="address" placeholder="Street address" required /><Field name="ownerName" placeholder="Owner or agency" required /><Field name="city" placeholder="City" required /><Field name="state" placeholder="State abbreviation" required /><Field name="zipCode" placeholder="ZIP" required /><Field name="estimatedValue" placeholder="Asking or estimated value" type="number" /><Field name="lotSize" placeholder="Lot size or acreage" /><select className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" defaultValue="NEEDS_VERIFICATION" name="opportunityStatus"><option value="NEEDS_VERIFICATION">Needs verification</option><option value="CONFIRMED_AVAILABLE">Confirmed available</option><option value="GOVERNMENT_SALE">Government sale</option></select><Field name="contactName" placeholder="Seller or agency contact" /><Field name="contactPhone" placeholder="Contact phone" /><Field name="contactEmail" placeholder="Contact email" type="email" /><Field name="sourceName" placeholder="Official government source" required /><Field name="sourceUrl" placeholder="Official source URL" required type="url" /><Field name="sourceRecordDate" placeholder="Record or listing date" required /><Field name="confidence" placeholder="Confidence 1–100" required type="number" /><textarea className="min-h-24 rounded-xl border p-3 text-sm" name="notes" placeholder="Zoning, utilities, document number, and research notes" /><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Save to county queue</button></form></aside>
    </section>
  </div></WorkspaceShell>;
}
