import Link from "next/link";
import { createDeveloperAction, createDeveloperProjectAction, generateDeveloperPricingRequestAction, importDevelopersCsvAction } from "@/app/actions";
import { CsvImportForm } from "@/app/csv-import-form";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { readDatabase, scoreDeveloperMatches } from "@/lib/database";

export const dynamic = "force-dynamic";
const money = (value?: number) => typeof value === "number" && value > 0 ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value) : "Unknown";
function crmValue(notes: string | undefined, label: string) { const line = notes?.split("\n").find((entry) => entry.startsWith(`${label}:`)); return line?.slice(label.length + 1).trim(); }
function Field({ name, placeholder, type = "text", required = false }: { name: string; placeholder: string; type?: string; required?: boolean }) { return <input className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" name={name} placeholder={placeholder} type={type} required={required} />; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center text-sm text-slate-500">{children}</p>; }

export default async function DevelopersPage({ searchParams }: { searchParams: Promise<{ developer?: string; q?: string }> }) {
  await requireOwner(); const params = await searchParams; const db = await readDatabase(); const query = params.q?.trim().toLowerCase() ?? "";
  const filtered = db.developers.filter((d) => [d.companyName, d.contactName, d.email, crmValue(d.notes, "Property types"), crmValue(d.notes, "Target markets")].filter(Boolean).some((value) => value?.toLowerCase().includes(query)));
  const selected = db.developers.find((d) => d.id === params.developer) ?? filtered[0] ?? db.developers[0];
  const purchases = selected ? db.developerProjects.filter((p) => p.developerId === selected.id) : [];
  const matches = selected ? (await Promise.all(db.properties.map(async (property) => ({ property, match: (await scoreDeveloperMatches(property.id, false)).find((item) => item.developerId === selected.id) })))).filter((item) => item.match).sort((a, b) => (b.match?.score ?? 0) - (a.match?.score ?? 0)) : [];
  return <WorkspaceShell active="developers"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Developer intelligence</p><h1 className="mt-1 text-3xl font-bold">Buyer Rolodex</h1><p className="mt-2 text-sm text-slate-600">Verify acquisition criteria, match properties, and manage follow-ups.</p></div><div className="flex gap-2"><a className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold" href="#import-buyers">Import CSV</a><a className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white" href="#add-buyer">Add developer</a></div></header>
    <section className="mt-6 grid gap-6 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><form><input className="w-full rounded-xl border bg-slate-50 px-4 py-2.5 text-sm" defaultValue={params.q} name="q" placeholder="Search company, market, asset…" /></form><p className="mt-3 text-xs text-slate-500">{filtered.length} developer{filtered.length === 1 ? "" : "s"} · A–Z Rolodex</p></div><div className="max-h-[720px] divide-y overflow-y-auto">{filtered.map((d) => { const active = d.id === selected?.id; return <Link className={`flex gap-3 p-4 ${active ? "bg-blue-50" : "hover:bg-slate-50"}`} href={`/developers?developer=${d.id}${params.q ? `&q=${encodeURIComponent(params.q)}` : ""}`} key={d.id}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full text-sm font-bold ${active ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-600"}`}>{d.companyName.slice(0, 2).toUpperCase()}</span><span className="min-w-0"><b className="block truncate">{d.companyName}</b><span className="mt-1 block truncate text-xs text-slate-500">{crmValue(d.notes, "Property types") || "Asset focus unknown"}</span><span className="mt-2 inline-block rounded-full bg-white px-2 py-1 text-[11px] font-semibold ring-1 ring-slate-200">{crmValue(d.notes, "Buying status") || "Discovered"}</span></span></Link>; })}{!filtered.length ? <div className="p-5"><Empty>No developers match this search.</Empty></div> : null}</div></aside>
      {selected ? <div className="space-y-6"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-6 lg:flex lg:items-center lg:justify-between"><div className="flex items-center gap-4"><span className="grid h-20 w-20 place-items-center rounded-2xl bg-slate-950 text-2xl font-bold text-white">{selected.companyName.slice(0, 2).toUpperCase()}</span><div><h2 className="text-2xl font-bold">{selected.companyName}</h2><p className="mt-1 text-sm text-slate-500">{selected.contactName || "Acquisitions contact needed"}</p><div className="mt-3 flex gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800">{crmValue(selected.notes, "Buying status") || "Researching"}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-800">{crmValue(selected.notes, "Evidence level") || "Unverified"}</span></div></div></div><div className="mt-5 text-sm text-slate-600 lg:mt-0 lg:text-right"><p>{selected.email || "Email needed"}</p><p>{selected.phone || "Phone needed"}</p><p>{selected.website || "Website needed"}</p></div></div>
        <div className="grid gap-5 p-5 lg:grid-cols-3"><article className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Current buy box</p><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Asset focus</dt><dd className="mt-1 font-semibold">{crmValue(selected.notes, "Property types") || "Needs verification"}</dd></div><div><dt className="text-slate-500">Markets</dt><dd className="mt-1 font-semibold">{crmValue(selected.notes, "Target markets") || "Needs verification"}</dd></div><div><dt className="text-slate-500">Acquisition criteria</dt><dd className="mt-1 font-semibold leading-5">{crmValue(selected.notes, "Acquisition criteria") || "Needs verification"}</dd></div><div><dt className="text-slate-500">Active signal</dt><dd className="mt-1 font-semibold">{crmValue(selected.notes, "Active acquisition signal") || "Not confirmed"}</dd></div></dl></article>
          <article className="rounded-2xl border p-5"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Matched properties</p><b className="text-2xl">{matches.length}</b></div><div className="mt-4 space-y-3">{matches.slice(0, 3).map(({ property, match }) => <div className="rounded-xl bg-slate-50 p-3" key={property.id}><div className="flex justify-between gap-3"><b className="truncate text-sm">{property.address}</b><b className="text-blue-700">{match?.score}</b></div><p className="mt-1 text-xs text-slate-500">{property.city}, {property.state} · {money(property.estimatedValue)}</p></div>)}{!matches.length ? <Empty>Add properties to generate matches.</Empty> : null}</div></article>
          <article className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Research & follow-ups</p><div className="mt-4 space-y-3 text-sm"><div className="rounded-xl bg-slate-50 p-3"><b>Verify acquisition criteria</b><p className="mt-1 text-xs text-slate-500">Evidence: {crmValue(selected.notes, "Evidence level") || "Unverified"}</p></div><div className="rounded-xl bg-slate-50 p-3"><b>Confirm active buying</b><p className="mt-1 text-xs text-slate-500">{crmValue(selected.notes, "Active acquisition signal") || "No direct signal recorded"}</p></div><div className="rounded-xl bg-slate-50 p-3"><b>Document purchase evidence</b><p className="mt-1 text-xs text-slate-500">{purchases.length} known acquisition{purchases.length === 1 ? "" : "s"}</p></div></div></article></div></section>
        <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Purchase history</h3><p className="mt-1 text-sm text-slate-500">Observed acquisitions show demonstrated behavior.</p></div><b className="h-fit rounded-full bg-slate-100 px-3 py-1">{purchases.length}</b></div><div className="mt-5 grid gap-3 md:grid-cols-2">{purchases.map((p) => <article className="rounded-xl border p-4" key={p.id}><b>{p.address}</b><p className="mt-1 text-sm text-slate-500">{p.city}, {p.state} {p.zipCode}</p><div className="mt-3 flex justify-between text-sm"><span>Purchase: {money(p.originalPurchasePrice)}</span><span>Finished: {money(p.newBuildSalePrice)}</span></div></article>)}{!purchases.length ? <Empty>No purchase evidence recorded yet.</Empty> : null}</div></section>
        {matches[0] ? <form action={generateDeveloperPricingRequestAction} className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><input type="hidden" name="propertyId" value={matches[0].property.id} /><input type="hidden" name="developerId" value={selected.id} /><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-blue-950">Best match: {matches[0].property.address}</b><p className="mt-1 text-sm text-blue-700">Create a reviewable draft. Nothing will be sent.</p></div><button className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Create outreach draft</button></div></form> : null}</div> : <section className="rounded-2xl border bg-white p-10"><Empty>Add or import your first developer.</Empty></section>}
    </section>
    <section className="mt-8 grid gap-6 xl:grid-cols-2"><details className="rounded-2xl border bg-white p-5 shadow-sm" id="import-buyers" open><summary className="cursor-pointer font-bold">Import developers from CSV</summary><div className="mt-4"><CsvImportForm action={importDevelopersCsvAction} buttonLabel="Import developers" helpText="The importer keeps company, market, asset focus, acquisition criteria, active-buying signal, website, valid contact information, and verification source. Unnecessary columns are discarded." /></div></details><details className="rounded-2xl border bg-white p-5 shadow-sm" id="add-buyer"><summary className="cursor-pointer font-bold">Add one developer manually</summary><form action={createDeveloperAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="companyName" placeholder="Company" required /><Field name="contactName" placeholder="Contact person" /><Field name="email" placeholder="Email" type="email" /><Field name="phone" placeholder="Phone" /><Field name="website" placeholder="Website" /><Field name="targetMarkets" placeholder="Markets" /><Field name="propertyTypes" placeholder="Asset focus" /><Field name="notes" placeholder="Acquisition criteria" /><input type="hidden" name="buyingStatus" value="Researching" /><input type="hidden" name="evidenceLevel" value="Unverified" /><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white sm:col-span-2">Add to Rolodex</button></form></details></section>
    {selected ? <details className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><summary className="cursor-pointer font-bold">Add purchase evidence for {selected.companyName}</summary><form action={createDeveloperProjectAction} className="mt-4 grid gap-3 md:grid-cols-4"><input type="hidden" name="developerId" value={selected.id} /><Field name="address" placeholder="Address" required /><Field name="city" placeholder="City" required /><Field name="state" placeholder="State" required /><Field name="zipCode" placeholder="ZIP" required /><Field name="originalPurchasePrice" placeholder="Purchase price" type="number" /><Field name="newBuildSalePrice" placeholder="Finished value" type="number" /><Field name="lotSquareFeet" placeholder="Lot square feet" type="number" /><Field name="notes" placeholder="Evidence source" /><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white md:col-span-4">Save evidence</button></form></details> : null}
  </div></WorkspaceShell>;
}
