"use client";

import { useActionState } from "react";
import { advanceStageAction, createBuyerDemandAction, createCampaignAction, recordGateAction, type PipelineActionState } from "@/app/pipeline-actions";

const initial: PipelineActionState = { status: "idle", message: "" };
const Result = ({ state }: { state: PipelineActionState }) => state.message ? <p className={state.status === "error" ? "text-sm text-red-700" : "text-sm text-emerald-700"}>{state.message}</p> : null;
const field = "rounded-lg border px-3 py-2 text-sm";

function ActionForm({ action, title, children }: { action: typeof createBuyerDemandAction; title: string; children: React.ReactNode }) { const [state, formAction, pending] = useActionState(action, initial); return <form action={formAction} className="space-y-3 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2>{children}<button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={pending}>{pending ? "Saving…" : "Save"}</button><Result state={state}/></form>; }

export function PipelineForms({ funnels, developers }: { funnels: { id: string; property: string }[]; developers: { id: string; name: string }[] }) {
  return <section className="mt-6 grid gap-6 xl:grid-cols-2">
    <ActionForm action={createBuyerDemandAction} title="Record buyer demand"><select className={`${field} w-full`} name="developerId" required><option value="">Developer</option>{developers.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><input className={`${field} w-full`} name="states" placeholder="States, comma separated" required/><input className={`${field} w-full`} name="counties" placeholder="Counties"/><input className={`${field} w-full`} name="zipCodes" placeholder="ZIP codes"/><input className={`${field} w-full`} name="assetTypes" placeholder="Asset types" required/><div className="grid grid-cols-3 gap-2"><input className={field} name="minPurchasePrice" placeholder="Min price"/><input className={field} name="maxPurchasePrice" placeholder="Max price"/><input className={field} name="maxAssignmentFee" placeholder="Max fee"/></div><input className={`${field} w-full`} name="strategy" placeholder="Strategy"/><input className={`${field} w-full`} name="sourceUrl" type="url" placeholder="HTTPS evidence URL" required/><input className={`${field} w-full`} name="expiresAt" type="datetime-local" required/><textarea className={`${field} w-full`} name="notes" placeholder="Criteria notes"/></ActionForm>
    <ActionForm action={createCampaignAction} title="Define a campaign"><input className={`${field} w-full`} name="name" placeholder="Campaign name" required/><div className="grid grid-cols-2 gap-2"><input className={field} name="state" maxLength={2} placeholder="State" required/><select className={field} name="type"><option value="SELLER_ACQUISITION">Seller acquisition</option><option value="BUYER_DISPOSITION">Buyer disposition</option></select></div><div className="grid grid-cols-2 gap-2"><input className={field} name="startsAt" type="datetime-local" required/><input className={field} name="endsAt" type="datetime-local" required/></div><textarea className={`${field} w-full`} name="audienceCriteria" placeholder="Audience criteria" required/><textarea className={`${field} w-full`} name="sourceRequirements" placeholder="Required public evidence" required/></ActionForm>
    <ActionForm action={recordGateAction} title="Record an evidence gate"><select className={`${field} w-full`} name="funnelId" required><option value="">Opportunity</option>{funnels.map((f) => <option key={f.id} value={f.id}>{f.property}</option>)}</select><div className="grid grid-cols-2 gap-2"><select className={field} name="type">{["PROPERTY_EVIDENCE","SELLER_CONTACT","UNDERWRITING","COMPLIANCE","CONTRACT","BUYER_COVERAGE","DISPOSITION","CLOSING"].map((v) => <option key={v}>{v}</option>)}</select><select className={field} name="status">{["PENDING","SATISFIED","FAILED","EXPIRED","WAIVED"].map((v) => <option key={v}>{v}</option>)}</select></div><input className={`${field} w-full`} name="sourceUrl" type="url" placeholder="HTTPS evidence URL"/><input className={`${field} w-full`} name="expiresAt" type="datetime-local"/><textarea className={`${field} w-full`} name="evidence" placeholder="Evidence notes" required/></ActionForm>
    <ActionForm action={advanceStageAction} title="Advance or route an opportunity"><select className={`${field} w-full`} name="funnelId" required><option value="">Opportunity</option>{funnels.map((f) => <option key={f.id} value={f.id}>{f.property}</option>)}</select><select className={`${field} w-full`} name="nextStage">{["RESEARCHABLE","BUYER_FIT","OUTREACH_READY","SELLER_ENGAGED","UNDERWRITING_READY","OFFER_READY","CONTRACTED","DISPOSITION_READY","CLOSED","DISQUALIFIED","NURTURE","ARCHIVED"].map((v) => <option key={v}>{v}</option>)}</select><textarea className={`${field} w-full`} name="reason" placeholder="Decision reason" required/></ActionForm>
  </section>;
}
