"use client";
import { useActionState, useState } from "react";
import { generateContractPacketAction, type WorkflowActionState } from "@/app/contract-workflow-actions";
const initial: WorkflowActionState = { status: "idle", message: "" };
export type BuilderTransaction = { id: string; propertyId: string; label: string; sellerName: string; propertyType: string; purchasePrice: number; assignmentFee: number };
export function ContractPacketBuilder({ transactions, companies, selectedTransactionId }: { transactions: BuilderTransaction[]; companies: { id: string; name: string }[]; selectedTransactionId?: string }) {
  const [state, action, pending] = useActionState(generateContractPacketAction, initial); const [structure, setStructure] = useState("ASSIGNMENT"); const selected = transactions.find((item) => item.id === selectedTransactionId) ?? transactions[0];
  if (!selected) return <p className="text-sm text-muted-foreground">Create a Deal transaction before generating a contract packet.</p>;
  const input = "mt-1 w-full rounded-xl border border-border bg-white px-3 py-2.5 text-sm";
  return <form action={action} className="grid gap-4 md:grid-cols-2"><input name="transactionId" type="hidden" value={selected.id}/><input name="propertyId" type="hidden" value={selected.propertyId}/>
    <label className="text-sm font-semibold md:col-span-2">Deal<select className={input} name="transactionId" defaultValue={selected.id}>{transactions.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>
    <label className="text-sm font-semibold">Closing structure<select className={input} name="structure" value={structure} onChange={e=>setStructure(e.target.value)}><option value="ASSIGNMENT">Assignment</option><option value="DOUBLE_CLOSE">Double close</option><option value="DIRECT_PURCHASE">Direct purchase</option></select></label>
    <label className="text-sm font-semibold">Title company<select className={input} name="titleCompanyId"><option value="">Select later</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label className="text-sm font-semibold">Seller legal name<input className={input} name="sellerLegalName" defaultValue={selected.sellerName} required/></label><label className="text-sm font-semibold">Buyer legal name<input className={input} name="buyerLegalName" defaultValue="Coleman & Co Holdings LLC d/b/a DealScout" required/></label>
    {structure === "ASSIGNMENT" ? <><label className="text-sm font-semibold">Assignee legal name<input className={input} name="assigneeLegalName" placeholder="Complete when buyer is selected"/></label><label className="text-sm font-semibold">Assignment fee<input className={input} name="assignmentFee" type="number" min="0" step="0.01" defaultValue={selected.assignmentFee}/></label><label className="text-sm font-semibold">Assignment deposit<input className={input} name="assignmentDeposit" type="number" min="0" step="0.01" defaultValue="5000"/></label><label className="text-sm font-semibold">Assignee diligence deadline<input className={input} name="assigneeDiligenceDeadline" type="date"/></label><label className="text-sm font-semibold">Proof of funds due<input className={input} name="proofOfFundsDueAt" type="date"/></label><label className="text-sm font-semibold">Approved contingency<input className={input} name="assignmentContingency" defaultValue="NONE"/></label></> : null}
    <label className="text-sm font-semibold">Purchase price<input className={input} name="purchasePrice" type="number" min="0" step="0.01" defaultValue={selected.purchasePrice} required/></label><label className="text-sm font-semibold">Closing date<input className={input} name="closingDate" type="date" required/></label><label className="text-sm font-semibold">Effective date<input className={input} name="effectiveDate" type="date"/></label><label className="text-sm font-semibold">Earnest money<input className={input} name="earnestMoney" type="number" min="0" step="0.01" defaultValue="100" required/></label><label className="text-sm font-semibold">Feasibility fee<input className={input} name="feasibilityFee" type="number" min="0" step="0.01" defaultValue="10" required/></label><label className="text-sm font-semibold">Feasibility days<input className={input} name="feasibilityDays" type="number" min="0" defaultValue="10" required/></label><label className="text-sm font-semibold">Access notice hours<input className={input} name="accessNoticeHours" type="number" min="0" defaultValue="24" required/></label>
    <label className="text-sm font-semibold md:col-span-2">Legal description<textarea className={input} name="legalDescription" placeholder="Use title-confirmed legal description" required/></label><input name="propertyType" type="hidden" value={selected.propertyType || "REAL PROPERTY"}/><input name="costAllocation" type="hidden" value="As shown on the settlement statement and agreed in writing"/><input name="sellerNoticeInformation" type="hidden" value="To be completed for this transaction"/><input name="buyerNoticeInformation" type="hidden" value="Coleman & Co Holdings LLC d/b/a DealScout"/><input name="brokerDisclosure" type="hidden" value="None unless separately identified in writing"/>
    <div className="flex items-center justify-between gap-4 border-t border-border pt-4 md:col-span-2"><p className={`text-sm ${state.status === "error" ? "text-red-700" : "text-emerald-700"}`}>{state.message}</p><button className="rounded-xl bg-primary px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={pending}>{pending ? "Generating…" : "Generate review packet"}</button></div>
  </form>;
}
