import Link from "next/link";
import { generateDeveloperPricingRequestAction } from "@/app/actions";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { readDatabase, scoreDeveloperMatches } from "@/lib/database";
import { propertyReadiness } from "@/lib/domain";

export const dynamic = "force-dynamic";
const money = (value?: number) => value ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value) : "Value unknown";

export default async function DispositionPage({ searchParams }: { searchParams: Promise<{ property?: string; sort?: string }> }) {
  await requireOwner();
  const [params, db] = await Promise.all([searchParams, readDatabase()]);
  const qualifiedIds = new Set(db.developers.filter((developer) => ["QUALIFIED", "PRIORITY"].includes(developer.qualificationStatus)).map((developer) => developer.id));
  const actionable = db.properties.filter((property) => propertyReadiness(property).actionable);
  const scored = await Promise.all(actionable.map(async (property) => ({ property, matches: (await scoreDeveloperMatches(property.id, false)).filter((match) => qualifiedIds.has(match.developerId)) })));
  scored.sort((a, b) => params.sort === "price" ? (b.property.estimatedValue ?? 0) - (a.property.estimatedValue ?? 0) : params.sort === "confidence" ? b.property.confidence - a.property.confidence : params.sort === "address" ? a.property.address.localeCompare(b.property.address) : (b.matches[0]?.score ?? 0) - (a.matches[0]?.score ?? 0) || b.property.confidence - a.property.confidence);
  const selected = scored.find((item) => item.property.id === params.property) ?? scored[0];
  const developerById = new Map(db.developers.map((developer) => [developer.id, developer]));
  const pendingDrafts = db.messageApprovals.filter((approval) => approval.status === "PENDING" && approval.subject?.startsWith("Pricing request:"));

  return <WorkspaceShell active="disposition"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <header className="border-b pb-6"><p className="text-sm font-semibold text-blue-700">Focused disposition engine</p><h1 className="mt-1 text-3xl font-bold">Property → qualified buyer → pricing draft</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Only source-backed, contactable opportunities and qualified buyers enter this workspace. Draft creation never sends a message.</p><form className="mt-4 flex gap-2"><select className="rounded-lg border bg-white px-3 py-2 text-sm" defaultValue={params.sort || "match"} name="sort"><option value="match">Best buyer match</option><option value="confidence">Highest confidence</option><option value="price">Highest price</option><option value="address">Address A–Z</option></select><button className="rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white">Sort</button></form></header>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Actionable properties</p><p className="mt-2 text-3xl font-bold">{actionable.length}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Qualified buyers</p><p className="mt-2 text-3xl font-bold">{qualifiedIds.size}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Pricing drafts awaiting review</p><p className="mt-2 text-3xl font-bold">{pendingDrafts.length}</p></article></section>
    {selected ? <section className="mt-6 grid gap-6 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Best Action Today</p><p className="mt-1 text-sm text-slate-500">Highest qualified match score, then property confidence.</p></div><div className="divide-y">{scored.map(({ property, matches }) => <Link className={`block p-4 ${property.id === selected.property.id ? "bg-blue-50" : "hover:bg-slate-50"}`} href={`/disposition?property=${property.id}`} key={property.id}><b className="block">{property.address}</b><span className="mt-1 block text-xs text-slate-500">{property.city}, {property.state} · {money(property.estimatedValue)}</span><span className="mt-2 inline-block rounded-full bg-white px-2 py-1 text-[11px] font-bold ring-1 ring-slate-200">Top match {matches[0]?.score ?? "none"}</span></Link>)}</div></aside>
      <div className="space-y-6"><article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Verified opportunity</p><h2 className="mt-1 text-2xl font-bold">{selected.property.address}</h2><p className="mt-1 text-sm text-slate-500">{selected.property.city}, {selected.property.state} {selected.property.zipCode} · Confidence {selected.property.confidence}%</p></div><a className="h-fit rounded-xl border px-4 py-2.5 text-sm font-bold text-blue-700" href={selected.property.sourceUrl} rel="noreferrer" target="_blank">Open source evidence</a></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Value</dt><dd className="mt-1 font-bold">{money(selected.property.estimatedValue)}</dd></div><div><dt className="text-slate-500">Seller contact</dt><dd className="mt-1 font-bold">{selected.property.contactName || selected.property.ownerName}</dd></div><div><dt className="text-slate-500">Contact method</dt><dd className="mt-1 font-bold">{selected.property.contactEmail || selected.property.contactPhone}</dd></div></dl></article>
        <article className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Qualified buyer matches</h2><p className="mt-1 text-sm text-slate-500">Scores use recorded geography, verified ownership or development history, and capacity. Review the evidence before creating a draft.</p><div className="mt-5 space-y-4">{selected.matches.map((match, index) => { const developer = developerById.get(match.developerId); if (!developer) return null; return <section className="rounded-xl border p-4" key={match.developerId}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-slate-500">Match #{index + 1}</p><h3 className="mt-1 text-lg font-bold">{developer.companyName}</h3><p className="text-sm text-slate-500">{developer.contactName || "Named contact missing"} · {developer.qualificationStatus}</p></div><span className="rounded-xl bg-blue-50 px-4 py-2 text-xl font-bold text-blue-800">{match.score}</span></div><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600">{match.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul><form action={generateDeveloperPricingRequestAction} className="mt-4"><input name="propertyId" type="hidden" value={selected.property.id} /><input name="developerId" type="hidden" value={developer.id} /><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Create draft for manual review</button></form></section>; })}{!selected.matches.length ? <p className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">No qualified buyer matches exist for this property. Add verified buyer evidence before proceeding.</p> : null}</div></article>
      </div></section> : <section className="mt-6 rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-bold">No disposition-ready property yet</h2><p className="mt-2 text-sm text-slate-500">A property needs confirmed availability, original evidence, current asking price, usable contact, and dated price/contact verification.</p><Link className="mt-5 inline-block rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white" href="/properties">Verify properties</Link></section>}
  </div></WorkspaceShell>;
}
