"use client";

import { useState } from "react";
import { buildLandDealWatchBrief, type LandDealWatchInput } from "@/lib/land-deal-watch";

const cash = (value: bigint | null) => value == null ? "Withheld — unsupported" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value) / 100);

export function LandDealWatchCard({ input }: { input: LandDealWatchInput }) {
  const [revision, setRevision] = useState(0);
  const brief = buildLandDealWatchBrief(input, revision);
  return <section className="mt-5 rounded-2xl border-2 border-blue-200 bg-white p-5 shadow-sm" id="land-deal-watch">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Land Deal Watch workflow</p><h2 className="mt-1 text-2xl font-bold">Acquisition decision brief</h2><p className="mt-1 text-sm text-slate-600">Discover → verify → underwrite → exit → contact → next action</p></div><span className="w-fit rounded-full bg-slate-950 px-3 py-2 text-xs font-bold text-white">{brief.status}</span></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><Block title="WHY THIS LEAD"><p>{brief.whyThisLead}</p></Block><Block title="WHY THIS MESSAGE"><p>{brief.whyThisMessage}</p><p className="mt-2 text-xs font-bold text-blue-700">ANGLE: {brief.angle}</p></Block></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><Block title="Evidence lanes"><Line label="Closed sales" text={brief.evidence.closedSales}/><Line label="Active asks" text={brief.evidence.activeAsks}/><Line label="Assessments" text={brief.evidence.assessments}/><Line label="AVMs" text={brief.evidence.avms}/></Block><Block title="Motivation reconstruction">{brief.motivation.length ? <ul className="list-disc space-y-1 pl-5">{brief.motivation.map(item => <li key={item}>{item}</li>)}</ul> : <p>No documented DOM, price-cut, relist, listing-language, or seller-stated motivation yet.</p>}</Block></div>
    <Block title="Property and buildability gates" className="mt-4"><div className="grid gap-2 sm:grid-cols-2">{brief.diligence.map(item => <div className="rounded-lg border p-3" key={item.label}><p className="font-bold">{item.state === "verified" ? "✓" : item.state === "conflict" ? "!" : "○"} {item.label}</p><p className="mt-1 text-slate-600">{item.detail}</p></div>)}</div>{brief.conflicts.length ? <div className="mt-3 rounded-lg bg-red-50 p-3 text-red-900"><b>Conflicting data — not silently resolved</b><ul className="mt-1 list-disc pl-5">{brief.conflicts.map(item => <li key={item}>{item}</li>)}</ul></div> : null}</Block>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><Block title="Exit and buyer value"><p>{brief.exit}</p><p className="mt-2">{brief.value}</p><p className="mt-2">{brief.spread}</p></Block><Block title="Acquisition range"><Line label="Opening" text={cash(brief.acquisitionRange.opening)}/><Line label="Target" text={cash(brief.acquisitionRange.target)}/><Line label="Ceiling" text={cash(brief.acquisitionRange.ceiling)}/><p className="mt-2 text-xs text-slate-500">Ranges are withheld unless closed-sale evidence supports value. Ceiling is a cap, not a promised offer.</p></Block></div>
    <Block title="Verified contact and property-specific outreach" className="mt-4"><p>{brief.contact}</p><details className="mt-3 rounded-lg border p-3" open><summary className="cursor-pointer font-bold">Call / text / email</summary><Line label="Call" text={brief.outreach.call}/><Line label="Text" text={brief.outreach.text}/><pre className="mt-2 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 font-sans text-sm">{brief.outreach.email}</pre></details><button className="mt-3 rounded-xl border border-blue-700 px-4 py-2 text-sm font-bold text-blue-700" onClick={() => setRevision(value => value + 1)} type="button">Regenerate with a different evidence-backed angle</button></Block>
    <div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-700">Exact next action</p><p className="mt-1 font-bold">{brief.nextAction}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><List title="ADVANCE IF" items={brief.advanceIf}/><List title="KILL IF" items={brief.killIf}/></div></div>
  </section>;
}
function Block({ title, className = "", children }: { title: string; className?: string; children: React.ReactNode }) { return <section className={`rounded-xl border border-slate-200 p-4 text-sm ${className}`}><h3 className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</h3><div className="mt-2 leading-6">{children}</div></section>; }
function Line({ label, text }: { label: string; text: string }) { return <p className="mt-2"><b>{label}:</b> {text}</p>; }
function List({ title, items }: { title: string; items: string[] }) { return <div><b className="text-xs">{title}</b><ul className="mt-1 list-disc pl-5 text-sm">{items.map(item => <li key={item}>{item}</li>)}</ul></div>; }
