import Link from "next/link";
import { WorkspaceShell } from "@/app/workspace-shell";
import { CreateTransactionForm, OwnerControls, ProfessionalDiligenceForm, RegisterDocumentForm } from "@/app/transactions/transaction-controls";
import { requireOwner } from "@/lib/auth";
import { readTransactionWorkspace } from "@/lib/transaction-control";

export const dynamic = "force-dynamic";
const money = (value: number | null) => value == null ? "Not set" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const date = (value: Date) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(value);

export default async function TransactionsPage({ searchParams }: { searchParams: Promise<{ transaction?: string }> }) {
  await requireOwner();
  const [params, workspace] = await Promise.all([searchParams, readTransactionWorkspace()]);
  const selected = workspace.transactions.find((item) => item.id === params.transaction) ?? workspace.transactions[0];
  const stopped = selected?.controlStatus === "STOPPED";
  return <WorkspaceShell active="transactions"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <header className="border-b pb-6"><p className="text-sm font-semibold text-blue-700">Owner-controlled execution</p><h1 className="mt-1 text-3xl font-bold">Transactions</h1><p className="mt-2 text-sm text-slate-600">Every deal starts on hold. Owner controls, documents, approvals, and events stay attached to the transaction.</p></header>
    <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Start a transaction</h2><div className="mt-4"><CreateTransactionForm developers={workspace.developers} properties={workspace.properties} /></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[330px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><b>{workspace.transactions.length} transaction{workspace.transactions.length === 1 ? "" : "s"}</b></div><div className="divide-y">{workspace.transactions.map((item) => <Link className={`block p-4 ${item.id === selected?.id ? "bg-blue-50" : "hover:bg-slate-50"}`} href={`/transactions?transaction=${item.id}`} key={item.id}><div className="flex items-center justify-between gap-3"><b>{item.property.address}</b><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${item.controlStatus === "STOPPED" ? "bg-red-100 text-red-800" : item.controlStatus === "ON_HOLD" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{item.controlStatus.replace("_", " ")}</span></div><p className="mt-1 text-xs text-slate-500">{item.status.replaceAll("_", " ")} · {item.jurisdictionState}</p></Link>)}{!workspace.transactions.length ? <p className="p-5 text-sm text-slate-500">No transactions yet.</p> : null}</div></aside>
      {selected ? <div className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">{selected.status.replaceAll("_", " ")}</p><h2 className="mt-1 text-2xl font-bold">{selected.property.address}</h2><p className="mt-1 text-sm text-slate-500">{selected.property.city}, {selected.property.state} · {selected.developer?.companyName || "Buyer not selected"}</p></div><span className={`h-fit rounded-xl px-4 py-2 text-sm font-bold ${stopped ? "bg-red-100 text-red-800" : selected.controlStatus === "ON_HOLD" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{selected.controlStatus.replace("_", " ")}</span></div><dl className="mt-6 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-slate-500">Seller price</dt><dd className="font-bold">{money(selected.targetSellerPrice)}</dd></div><div><dt className="text-xs text-slate-500">Buyer price</dt><dd className="font-bold">{money(selected.targetBuyerPrice)}</dd></div><div><dt className="text-xs text-slate-500">Target fee</dt><dd className="font-bold">{money(selected.targetAssignmentFee)}</dd></div></dl>{selected.ownerHoldReason ? <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{selected.ownerHoldReason}</p> : null}</section>
        <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Owner controls</h2><div className="mt-4"><OwnerControls stopped={stopped} transactionId={selected.id} /></div></section>
        <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Documentation</h2><span className="text-sm font-bold">{selected.documents.length}</span></div><div className="mt-4"><RegisterDocumentForm stopped={stopped} transactionId={selected.id} /></div><div className="mt-4 divide-y">{selected.documents.map((document) => <div className="flex flex-col justify-between gap-2 py-3 sm:flex-row" key={document.id}><div><b>{document.title}</b><p className="text-xs text-slate-500">{document.type} · version {document.version} · {document.status.replace("_", " ")}</p></div>{document.sourceUrl ? <a className="text-sm font-bold text-blue-700 underline" href={document.sourceUrl} rel="noreferrer" target="_blank">Open document</a> : null}</div>)}{!selected.documents.length ? <p className="py-4 text-sm text-slate-500">No documents registered.</p> : null}</div></section>
        <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Professional diligence</h2><p className="mt-1 text-sm text-slate-500">Register reviewed artifacts only. Public research cannot satisfy enhanced diligence.</p><div className="mt-4"><ProfessionalDiligenceForm stopped={stopped} transactionId={selected.id} /></div><div className="mt-4 divide-y">{selected.diligenceReviews.flatMap((review) => review.professionalArtifacts.map((artifact) => <div className="flex justify-between gap-3 py-3" key={artifact.id}><div><b>{artifact.category}</b><p className="text-xs text-slate-500">{artifact.professionalName} · {artifact.professionalRole} · {date(artifact.verifiedAt)}</p></div><a className="text-sm font-bold text-blue-700 underline" href={artifact.sourceUrl} rel="noreferrer" target="_blank">Open artifact</a></div>))}</div></section>
        <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Approvals · {selected.approvals.length}</h2><div className="mt-3 divide-y">{selected.approvals.map((approval) => <div className="py-3" key={approval.id}><b className="text-sm">{approval.type.replaceAll("_", " ")}</b><p className="text-xs text-slate-500">{approval.status} · requested {date(approval.requestedAt)}</p></div>)}{!selected.approvals.length ? <p className="text-sm text-slate-500">No approvals requested.</p> : null}</div></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Audit history · {selected.auditEvents.length}</h2><div className="mt-3 divide-y">{selected.auditEvents.map((event) => <div className="py-3" key={event.id}><b className="text-sm">#{event.sequence} {event.summary}</b><p className="text-xs text-slate-500">{event.actor} · {date(event.occurredAt)}</p></div>)}</div></article></section>
      </div> : <div className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Create a transaction to start the controlled workflow.</div>}
    </section>
  </div></WorkspaceShell>;
}
