CREATE TYPE "CountyCoverageStatus" AS ENUM ('AUTOMATED','MANUAL_ONLY','RESTRICTED','PAYWALLED','TEMPORARILY_UNAVAILABLE','NOT_FOUND','NEEDS_REVIEW');
CREATE TYPE "CountyAutomationStatus" AS ENUM ('PERMITTED','RESTRICTED','UNKNOWN','PROHIBITED');
CREATE TYPE "CountyAgencyType" AS ENUM ('ASSESSOR','APPRAISAL_DISTRICT','PROPERTY_APPRAISER','TAX','GIS','RECORDER','DEEDS','TREASURER','AUDITOR','OTHER');
CREATE TYPE "CountyObservationStatus" AS ENUM ('VERIFIED','CONFLICTED','NEEDS_MANUAL_VERIFICATION','REJECTED','EXPIRED');
CREATE TYPE "CountyEntityMatchStatus" AS ENUM ('PROPOSED','NEEDS_MANUAL_VERIFICATION','VERIFIED','REJECTED','CONFLICTED');

CREATE TABLE "CountySourceRegistry" ("id" TEXT PRIMARY KEY,"stateCode" TEXT NOT NULL,"countyName" TEXT NOT NULL,"countyEquivalentType" TEXT,"fipsCode" TEXT NOT NULL,"coverageStatus" "CountyCoverageStatus" NOT NULL DEFAULT 'NEEDS_REVIEW',"coverageReason" TEXT,"manualSearchInstructions" TEXT,"lastAccessibilityCheckAt" TIMESTAMP(3),"lastSuccessfulRunAt" TIMESTAMP(3),"nextReviewAt" TIMESTAMP(3),"failureReason" TEXT,"reviewedBy" TEXT,"reviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "CountySourceRegistry_fipsCode_key" ON "CountySourceRegistry"("fipsCode");
CREATE UNIQUE INDEX "CountySourceRegistry_stateCode_countyName_key" ON "CountySourceRegistry"("stateCode","countyName");
CREATE INDEX "CountySourceRegistry_coverageStatus_nextReviewAt_idx" ON "CountySourceRegistry"("coverageStatus","nextReviewAt");

CREATE TABLE "CountyOfficialSource" ("id" TEXT PRIMARY KEY,"registryId" TEXT NOT NULL,"version" INTEGER NOT NULL,"agencyName" TEXT NOT NULL,"agencyType" "CountyAgencyType" NOT NULL,"officialDomain" TEXT NOT NULL,"delegationEvidenceUrl" TEXT,"propertySearchUrl" TEXT,"parcelGisUrl" TEXT,"taxUrl" TEXT,"recorderUrl" TEXT,"bulkDataUrl" TEXT,"queryEndpointUrl" TEXT,"termsUrl" TEXT,"robotsUrl" TEXT,"accessMethod" TEXT NOT NULL,"authenticationRequired" BOOLEAN NOT NULL DEFAULT false,"subscriptionRequired" BOOLEAN NOT NULL DEFAULT false,"costStatus" TEXT,"automationStatus" "CountyAutomationStatus" NOT NULL DEFAULT 'UNKNOWN',"robotsStatus" TEXT,"rateLimitStatus" TEXT,"supportedSearches" TEXT[],"availableFields" TEXT[],"coverageNotes" TEXT,"sourceConfidence" INTEGER NOT NULL,"adapterVersion" TEXT,"parserVersion" TEXT,"effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"supersededAt" TIMESTAMP(3),"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CountyOfficialSource_registryId_fkey" FOREIGN KEY ("registryId") REFERENCES "CountySourceRegistry"("id") ON DELETE RESTRICT);
CREATE UNIQUE INDEX "CountyOfficialSource_registryId_agencyName_agencyType_version_key" ON "CountyOfficialSource"("registryId","agencyName","agencyType","version");
CREATE INDEX "CountyOfficialSource_registryId_supersededAt_idx" ON "CountyOfficialSource"("registryId","supersededAt");
CREATE INDEX "CountyOfficialSource_automationStatus_idx" ON "CountyOfficialSource"("automationStatus");

CREATE TABLE "CountySourceCheck" ("id" TEXT PRIMARY KEY,"sourceId" TEXT NOT NULL,"status" "CountyCoverageStatus" NOT NULL,"httpStatus" INTEGER,"retrievalMethod" TEXT NOT NULL,"responseHash" TEXT,"failureReason" TEXT,"circuitOpenUntil" TIMESTAMP(3),"retryCount" INTEGER NOT NULL DEFAULT 0,"checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CountySourceCheck_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "CountyOfficialSource"("id") ON DELETE RESTRICT);
CREATE INDEX "CountySourceCheck_sourceId_checkedAt_idx" ON "CountySourceCheck"("sourceId","checkedAt");
CREATE INDEX "CountySourceCheck_status_circuitOpenUntil_idx" ON "CountySourceCheck"("status","circuitOpenUntil");

ALTER TABLE "Property" ADD COLUMN "countyRegistryId" TEXT;
ALTER TABLE "DeveloperProject" ADD COLUMN "countyRegistryId" TEXT;
ALTER TABLE "Property" ADD CONSTRAINT "Property_countyRegistryId_fkey" FOREIGN KEY ("countyRegistryId") REFERENCES "CountySourceRegistry"("id") ON DELETE SET NULL;
ALTER TABLE "DeveloperProject" ADD CONSTRAINT "DeveloperProject_countyRegistryId_fkey" FOREIGN KEY ("countyRegistryId") REFERENCES "CountySourceRegistry"("id") ON DELETE SET NULL;
CREATE INDEX "Property_countyRegistryId_idx" ON "Property"("countyRegistryId");
CREATE INDEX "DeveloperProject_countyRegistryId_idx" ON "DeveloperProject"("countyRegistryId");

CREATE TABLE "CountyFactObservation" ("id" TEXT PRIMARY KEY,"sourceId" TEXT NOT NULL,"propertyId" TEXT,"developerProjectId" TEXT,"fieldName" TEXT NOT NULL,"value" JSONB NOT NULL,"status" "CountyObservationStatus" NOT NULL DEFAULT 'NEEDS_MANUAL_VERIFICATION',"sourceRecordId" TEXT,"queryKeyHash" TEXT NOT NULL,"rawRecordHash" TEXT NOT NULL,"effectiveYear" INTEGER,"observedAt" TIMESTAMP(3) NOT NULL,"confidence" INTEGER NOT NULL,"conflictDetails" JSONB,"retrievalMethod" TEXT NOT NULL,"adapterVersion" TEXT NOT NULL,"parserVersion" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CountyFactObservation_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "CountyOfficialSource"("id") ON DELETE RESTRICT,CONSTRAINT "CountyFactObservation_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT,CONSTRAINT "CountyFactObservation_developerProjectId_fkey" FOREIGN KEY ("developerProjectId") REFERENCES "DeveloperProject"("id") ON DELETE RESTRICT,CONSTRAINT "CountyFactObservation_target_check" CHECK (("propertyId" IS NOT NULL)::int + ("developerProjectId" IS NOT NULL)::int = 1),CONSTRAINT "CountyFactObservation_confidence_check" CHECK ("confidence" BETWEEN 0 AND 100));
CREATE UNIQUE INDEX "CountyFactObservation_sourceId_queryKeyHash_fieldName_rawRecordHash_key" ON "CountyFactObservation"("sourceId","queryKeyHash","fieldName","rawRecordHash");
CREATE INDEX "CountyFactObservation_propertyId_fieldName_observedAt_idx" ON "CountyFactObservation"("propertyId","fieldName","observedAt");
CREATE INDEX "CountyFactObservation_developerProjectId_fieldName_observedAt_idx" ON "CountyFactObservation"("developerProjectId","fieldName","observedAt");
CREATE INDEX "CountyFactObservation_status_observedAt_idx" ON "CountyFactObservation"("status","observedAt");

CREATE TABLE "CountyEntityMatch" ("id" TEXT PRIMARY KEY,"sourceId" TEXT NOT NULL,"developerId" TEXT NOT NULL,"propertyId" TEXT,"developerProjectId" TEXT,"status" "CountyEntityMatchStatus" NOT NULL DEFAULT 'NEEDS_MANUAL_VERIFICATION',"matchedName" TEXT NOT NULL,"rationale" TEXT NOT NULL,"supportingEvidence" JSONB NOT NULL,"conflictingEvidence" JSONB,"confidence" INTEGER NOT NULL,"observedAt" TIMESTAMP(3) NOT NULL,"reviewedBy" TEXT,"reviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CountyEntityMatch_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "CountyOfficialSource"("id") ON DELETE RESTRICT,CONSTRAINT "CountyEntityMatch_developerId_fkey" FOREIGN KEY ("developerId") REFERENCES "Developer"("id") ON DELETE RESTRICT,CONSTRAINT "CountyEntityMatch_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT,CONSTRAINT "CountyEntityMatch_developerProjectId_fkey" FOREIGN KEY ("developerProjectId") REFERENCES "DeveloperProject"("id") ON DELETE RESTRICT,CONSTRAINT "CountyEntityMatch_target_check" CHECK (("propertyId" IS NOT NULL)::int + ("developerProjectId" IS NOT NULL)::int = 1),CONSTRAINT "CountyEntityMatch_confidence_check" CHECK ("confidence" BETWEEN 0 AND 100),CONSTRAINT "CountyEntityMatch_verified_review_check" CHECK ("status" <> 'VERIFIED' OR ("reviewedBy" IS NOT NULL AND "reviewedAt" IS NOT NULL)));
CREATE INDEX "CountyEntityMatch_developerId_status_observedAt_idx" ON "CountyEntityMatch"("developerId","status","observedAt");
CREATE INDEX "CountyEntityMatch_propertyId_status_idx" ON "CountyEntityMatch"("propertyId","status");
