CREATE TYPE "BuyerPriceStatus" AS ENUM ('INDICATIVE','CONDITIONAL','DOCUMENTED','COMMITTED','EXPIRED');
CREATE TYPE "BuyerPermissionStatus" AS ENUM ('UNKNOWN','GRANTED','DENIED','REVOKED','EXPIRED');
CREATE TYPE "BuyerIssueStatus" AS ENUM ('OPEN','DISPUTED','RESOLVED','DISMISSED');

ALTER TABLE "BuyerDemandVersion" ADD COLUMN "excludedAreas" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "marketPolygons" JSONB, ADD COLUMN "minCompletedValueCents" BIGINT, ADD COLUMN "maxCompletedValueCents" BIGINT, ADD COLUMN "minLotWidthFeet" DOUBLE PRECISION, ADD COLUMN "maxLotWidthFeet" DOUBLE PRECISION, ADD COLUMN "minLotDepthFeet" DOUBLE PRECISION, ADD COLUMN "maxLotDepthFeet" DOUBLE PRECISION, ADD COLUMN "minFrontageFeet" DOUBLE PRECISION, ADD COLUMN "accessPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "utilityPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "zoningPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "floodPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "entitlementPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "redevelopmentPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "requiredClosingDays" INTEGER, ADD COLUMN "assignmentAcceptance" TEXT, ADD COLUMN "doubleCloseAcceptance" TEXT, ADD COLUMN "earnestMoneyExpectationCents" BIGINT, ADD COLUMN "inspectionRequirements" TEXT, ADD COLUMN "decisionMakerName" TEXT, ADD COLUMN "approvedChannel" "EngagementChannel", ADD COLUMN "currentBuyingStatus" TEXT, ADD COLUMN "criteriaConfirmedAt" TIMESTAMP(3);
ALTER TABLE "BuyerCapacityEvidence" ADD COLUMN "artifactHash" TEXT, ADD COLUMN "observedAt" TIMESTAMP(3);
UPDATE "BuyerCapacityEvidence" SET "observedAt" = "createdAt" WHERE "observedAt" IS NULL;
ALTER TABLE "BuyerCapacityEvidence" ALTER COLUMN "observedAt" SET NOT NULL;
ALTER TABLE "BuyerReliabilityEvidence" ADD COLUMN "retrades" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "responsesMeasured" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "averageResponseHours" DOUBLE PRECISION, ADD COLUMN "unresolvedIssues" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE "BuyerPropertyPriceEvidence" ("id" TEXT PRIMARY KEY,"developerId" TEXT NOT NULL,"demandVersionId" TEXT NOT NULL,"funnelId" TEXT NOT NULL,"version" INTEGER NOT NULL,"status" "BuyerPriceStatus" NOT NULL,"lowCents" BIGINT NOT NULL,"baseCents" BIGINT NOT NULL,"highCents" BIGINT NOT NULL,"assumptions" TEXT[],"sourceUrl" TEXT NOT NULL,"observedAt" TIMESTAMP(3) NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"reviewedBy" TEXT,"reviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BuyerPropertyPriceEvidence_developerId_fkey" FOREIGN KEY ("developerId") REFERENCES "Developer"("id") ON DELETE RESTRICT,CONSTRAINT "BuyerPropertyPriceEvidence_demandVersionId_fkey" FOREIGN KEY ("demandVersionId") REFERENCES "BuyerDemandVersion"("id") ON DELETE RESTRICT,CONSTRAINT "BuyerPropertyPriceEvidence_funnelId_fkey" FOREIGN KEY ("funnelId") REFERENCES "AcquisitionFunnel"("id") ON DELETE RESTRICT,CONSTRAINT "BuyerPropertyPriceEvidence_range_check" CHECK ("lowCents" <= "baseCents" AND "baseCents" <= "highCents" AND "lowCents" >= 0),CONSTRAINT "BuyerPropertyPriceEvidence_review_check" CHECK ("status" NOT IN ('DOCUMENTED','COMMITTED') OR ("reviewedBy" IS NOT NULL AND "reviewedAt" IS NOT NULL)));
CREATE UNIQUE INDEX "BuyerPropertyPriceEvidence_developerId_funnelId_version_key" ON "BuyerPropertyPriceEvidence"("developerId","funnelId","version");
CREATE INDEX "BuyerPropertyPriceEvidence_funnelId_status_expiresAt_idx" ON "BuyerPropertyPriceEvidence"("funnelId","status","expiresAt");

CREATE TABLE "BuyerCommunicationPermission" ("id" TEXT PRIMARY KEY,"developerId" TEXT NOT NULL,"channel" "EngagementChannel" NOT NULL,"status" "BuyerPermissionStatus" NOT NULL DEFAULT 'UNKNOWN',"sourceUrl" TEXT,"capturedAt" TIMESTAMP(3) NOT NULL,"expiresAt" TIMESTAMP(3),"reviewedBy" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BuyerCommunicationPermission_developerId_fkey" FOREIGN KEY ("developerId") REFERENCES "Developer"("id") ON DELETE RESTRICT);
CREATE INDEX "BuyerCommunicationPermission_developerId_channel_capturedAt_idx" ON "BuyerCommunicationPermission"("developerId","channel","capturedAt");
CREATE TABLE "BuyerPerformanceIssue" ("id" TEXT PRIMARY KEY,"developerId" TEXT NOT NULL,"type" TEXT NOT NULL,"status" "BuyerIssueStatus" NOT NULL DEFAULT 'OPEN',"occurredAt" TIMESTAMP(3) NOT NULL,"description" TEXT NOT NULL,"sourceUrl" TEXT NOT NULL,"resolution" TEXT,"resolvedAt" TIMESTAMP(3),"reviewedBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BuyerPerformanceIssue_developerId_fkey" FOREIGN KEY ("developerId") REFERENCES "Developer"("id") ON DELETE RESTRICT);
CREATE INDEX "BuyerPerformanceIssue_developerId_status_occurredAt_idx" ON "BuyerPerformanceIssue"("developerId","status","occurredAt");

CREATE TABLE "BuyerReliabilityScoreConfiguration" ("id" TEXT PRIMARY KEY,"version" INTEGER NOT NULL,"status" "ProfitPriorityConfigurationStatus" NOT NULL DEFAULT 'DRAFT',"financialCapacityWeight" INTEGER NOT NULL,"marketActivityWeight" INTEGER NOT NULL,"criteriaSpecificityWeight" INTEGER NOT NULL,"responseTimeWeight" INTEGER NOT NULL,"closingRateWeight" INTEGER NOT NULL,"pofFreshnessWeight" INTEGER NOT NULL,"retradePenaltyWeight" INTEGER NOT NULL,"failedClosingPenaltyWeight" INTEGER NOT NULL,"unresolvedIssuePenaltyWeight" INTEGER NOT NULL,"reason" TEXT NOT NULL,"effectiveAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "BuyerReliabilityScoreConfiguration_version_key" ON "BuyerReliabilityScoreConfiguration"("version");
CREATE TABLE "BuyerReliabilityScoreHistory" ("id" TEXT PRIMARY KEY,"developerId" TEXT NOT NULL,"demandVersionId" TEXT NOT NULL,"reliabilityEvidenceId" TEXT NOT NULL,"configurationId" TEXT NOT NULL,"version" INTEGER NOT NULL,"totalScore" INTEGER NOT NULL,"componentScores" JSONB NOT NULL,"inputSnapshot" JSONB NOT NULL,"reasons" TEXT[],"blockers" TEXT[],"calculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3) NOT NULL,"calculatedBy" TEXT NOT NULL,CONSTRAINT "BuyerReliabilityScoreHistory_developerId_fkey" FOREIGN KEY ("developerId") REFERENCES "Developer"("id") ON DELETE RESTRICT,CONSTRAINT "BuyerReliabilityScoreHistory_demandVersionId_fkey" FOREIGN KEY ("demandVersionId") REFERENCES "BuyerDemandVersion"("id") ON DELETE RESTRICT,CONSTRAINT "BuyerReliabilityScoreHistory_reliabilityEvidenceId_fkey" FOREIGN KEY ("reliabilityEvidenceId") REFERENCES "BuyerReliabilityEvidence"("id") ON DELETE RESTRICT,CONSTRAINT "BuyerReliabilityScoreHistory_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "BuyerReliabilityScoreConfiguration"("id") ON DELETE RESTRICT);
CREATE UNIQUE INDEX "BuyerReliabilityScoreHistory_developerId_version_key" ON "BuyerReliabilityScoreHistory"("developerId","version");
CREATE INDEX "BuyerReliabilityScoreHistory_totalScore_expiresAt_idx" ON "BuyerReliabilityScoreHistory"("totalScore","expiresAt");
