import Link from "next/link";
import { DevelopmentRadarMapShell } from "@/app/research/development-radar-map-shell";
import { ResearchScanForm } from "@/app/research/research-scan-form";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { governmentSources, readGovernmentResearch } from "@/lib/government-research";

export const dynamic = "force-dynamic";
const money = (value: string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value));
const periodLabel = (period: string) => `${period.slice(0, 4)}-${period.slice(4)}`;

export default async function ResearchPage({ searchParams }: { searchParams: Promise<{ sort?: string; page?: string }> }) {
  await requireOwner();
  const params = await searchParams;
  const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const data = await readGovernmentResearch({ listingPage: page, listingPageSize: 250 });
  const sort = params.sort || "rank";
  const rankCategory = { rank: "Momentum", growth: "Growth", units: "Current units", value: "Permit value", county: "County A–Z" }[sort] || "Momentum";
  const signals = data.signals.toSorted((a, b) => sort === "growth" ? (b.growthPct ?? -Infinity) - (a.growthPct ?? -Infinity) : sort === "units" ? b.currentUnits - a.currentUnits : sort === "value" ? Number(b.currentValue) - Number(a.currentValue) : sort === "county" ? a.countyName.localeCompare(b.countyName) : a.rank - b.rank);
  const period = data.signals[0]?.period;
  return <WorkspaceShell active="research"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <header className="flex flex-col gap-5 border-b pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-blue-700">Government-source research</p><h1 className="mt-1 text-3xl font-bold">Nationwide Development Radar</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Census permit activity identifies counties with meaningful construction momentum. These are market signals, not properties for sale.</p></div><ResearchScanForm /></header>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Latest period</p><p className="mt-2 text-2xl font-bold">{period ? periodLabel(period) : "Not scanned"}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Counties ranked</p><p className="mt-2 text-2xl font-bold">{data.signals.length}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Last run</p><p className="mt-2 text-lg font-bold">{data.latestRun?.status || "Never"}</p><p className="mt-1 text-xs text-slate-500">{data.latestRun?.finishedAt ? new Date(data.latestRun.finishedAt).toLocaleString() : "Run the first scan to populate the radar."}</p></article></section>
    <DevelopmentRadarMapShell listings={data.listings} rankCategory={rankCategory} signals={signals} />
    {data.listingPagination.pages > 1 ? <nav aria-label="Map property pages" className="mt-3 flex items-center justify-between rounded-xl border bg-white px-4 py-3 text-sm"><span>Mapped properties {(page - 1) * data.listingPagination.pageSize + 1}–{Math.min(page * data.listingPagination.pageSize, data.listingPagination.total)} of {data.listingPagination.total}</span><div className="flex gap-2">{page > 1 ? <Link className="rounded-lg border px-3 py-2 font-bold" href={`/research?sort=${sort}&page=${page - 1}`}>Previous map page</Link> : null}{page < data.listingPagination.pages ? <Link className="rounded-lg bg-slate-950 px-3 py-2 font-bold text-white" href={`/research?sort=${sort}&page=${page + 1}`}>Next map page</Link> : null}</div></nav> : null}
    <section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row sm:items-end"><div><h2 className="text-xl font-bold">County development momentum</h2><p className="mt-1 text-sm text-slate-500">Rank combines current permitted units with positive year-over-year unit growth. Minimum activity: 10 units. {data.dataPeriod ? `Showing completed Census period ${data.dataPeriod}.` : ""}</p><p className="mt-2 text-xs font-bold text-blue-700">Ranks currently reflect: {rankCategory}</p></div><form><select className="rounded-lg border px-3 py-2 text-sm" defaultValue={sort} name="sort"><option value="rank">Rank</option><option value="growth">Growth</option><option value="units">Current units</option><option value="value">Permit value</option><option value="county">County A–Z</option></select><button className="ml-2 rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white">Sort</button></form></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">{rankCategory} rank</th><th className="p-4">County</th><th className="p-4">Current units</th><th className="p-4">Prior year</th><th className="p-4">Growth</th><th className="p-4">Permit value</th><th className="p-4">Evidence</th></tr></thead><tbody className="divide-y">{signals.slice(0, 75).map((signal, index) => <tr key={signal.id}><td className="p-4"><span className="font-bold">#{index + 1}</span><span className="block text-[11px] text-slate-500">in {rankCategory}</span></td><td className="p-4"><Link className="font-bold text-blue-800 underline decoration-blue-200 underline-offset-4" href={`/research/${signal.fips}`}>{signal.countyName}</Link><span className="block text-xs text-slate-500">{signal.stateName} · FIPS {signal.fips}</span></td><td className="p-4 font-semibold">{signal.currentUnits.toLocaleString()}</td><td className="p-4 text-slate-500">{signal.priorUnits?.toLocaleString() ?? "No baseline"}</td><td className={`p-4 font-bold ${signal.growthPct === null ? "text-slate-500" : signal.growthPct >= 0 ? "text-emerald-700" : "text-red-700"}`}>{signal.growthPct === null ? "New / no baseline" : `${signal.growthPct >= 0 ? "+" : ""}${signal.growthPct.toFixed(1)}%`}</td><td className="p-4">{money(signal.currentValue)}</td><td className="p-4"><a className="font-bold text-blue-700 underline" href={signal.sourceUrl} rel="noreferrer" target="_blank">Census file</a></td></tr>)}{!signals.length ? <tr><td className="p-10 text-center text-slate-500" colSpan={7}>No market signals yet. Run the nationwide permit scan.</td></tr> : null}</tbody></table></div></section>
    <details className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><summary className="cursor-pointer text-xl font-bold">Research source connections</summary><p className="mt-1 text-sm text-slate-500">Only approved sources are used. Open this when you need to inspect connector status.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{governmentSources.map((source) => <article className="rounded-xl border p-4" key={source.name}><div className="flex items-start justify-between gap-3"><div><b>{source.name}</b><p className="mt-2 text-sm leading-5 text-slate-500">{source.purpose}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${source.status === "Connected" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{source.status}</span></div><a className="mt-3 inline-block text-xs font-bold text-blue-700 underline" href={source.url} rel="noreferrer" target="_blank">Open official source</a></article>)}</div></details>
  </div></WorkspaceShell>;
}
