import Link from "next/link";
import { ResearchScanForm } from "@/app/research/research-scan-form";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { governmentSources, readGovernmentResearch } from "@/lib/government-research";

export const dynamic = "force-dynamic";
const money = (value: string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value));
const periodLabel = (period: string) => `${period.slice(0, 4)}-${period.slice(4)}`;

export default async function ResearchPage() {
  await requireOwner();
  const data = await readGovernmentResearch();
  const period = data.signals[0]?.period;
  return <WorkspaceShell active="research"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <header className="flex flex-col gap-5 border-b pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-blue-700">Government-source research</p><h1 className="mt-1 text-3xl font-bold">Nationwide Development Radar</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Census permit activity identifies counties with meaningful construction momentum. These are market signals, not properties for sale.</p></div><ResearchScanForm /></header>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Latest period</p><p className="mt-2 text-2xl font-bold">{period ? periodLabel(period) : "Not scanned"}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Counties ranked</p><p className="mt-2 text-2xl font-bold">{data.signals.length}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Last run</p><p className="mt-2 text-lg font-bold">{data.latestRun?.status || "Never"}</p><p className="mt-1 text-xs text-slate-500">{data.latestRun?.finishedAt ? new Date(data.latestRun.finishedAt).toLocaleString() : "Run the first scan to populate the radar."}</p></article></section>
    <section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-bold">County development momentum</h2><p className="mt-1 text-sm text-slate-500">Rank combines current permitted units with positive year-over-year unit growth. Minimum activity: 10 units. {data.dataPeriod ? `Showing completed Census period ${data.dataPeriod}.` : ""}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Rank</th><th className="p-4">County</th><th className="p-4">Current units</th><th className="p-4">Prior year</th><th className="p-4">Growth</th><th className="p-4">Permit value</th><th className="p-4">Evidence</th></tr></thead><tbody className="divide-y">{data.signals.slice(0, 75).map((signal) => <tr key={signal.id}><td className="p-4 font-bold">#{signal.rank}</td><td className="p-4"><Link className="font-bold text-blue-800 underline decoration-blue-200 underline-offset-4" href={`/research/${signal.fips}`}>{signal.countyName}</Link><span className="block text-xs text-slate-500">{signal.stateName} · FIPS {signal.fips}</span></td><td className="p-4 font-semibold">{signal.currentUnits.toLocaleString()}</td><td className="p-4 text-slate-500">{signal.priorUnits?.toLocaleString() ?? "No baseline"}</td><td className={`p-4 font-bold ${signal.growthPct === null ? "text-slate-500" : signal.growthPct >= 0 ? "text-emerald-700" : "text-red-700"}`}>{signal.growthPct === null ? "New / no baseline" : `${signal.growthPct >= 0 ? "+" : ""}${signal.growthPct.toFixed(1)}%`}</td><td className="p-4">{money(signal.currentValue)}</td><td className="p-4"><a className="font-bold text-blue-700 underline" href={signal.sourceUrl} rel="noreferrer" target="_blank">Census file</a></td></tr>)}{!data.signals.length ? <tr><td className="p-10 text-center text-slate-500" colSpan={7}>No market signals yet. Run the nationwide permit scan.</td></tr> : null}</tbody></table></div></section>
    <section className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Approved federal source catalog</h2><p className="mt-1 text-sm text-slate-500">Only official government sources. Each connector is enabled separately after its data format is verified.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{governmentSources.map((source) => <article className="rounded-xl border p-4" key={source.name}><div className="flex items-start justify-between gap-3"><div><b>{source.name}</b><p className="mt-2 text-sm leading-5 text-slate-500">{source.purpose}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${source.status === "Connected" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{source.status}</span></div><a className="mt-3 inline-block text-xs font-bold text-blue-700 underline" href={source.url} rel="noreferrer" target="_blank">Open official source</a></article>)}</div></section>
  </div></WorkspaceShell>;
}
