"use server";
import { revalidatePath } from "next/cache";
import { requireOwner } from "@/lib/auth";
import { createWeightChangeProposal, recordTransactionOutcome, reviewWeightChangeProposal } from "@/lib/outcome-learning";
import type { OutcomeReasonCode } from "@/lib/outcome-reasons";
import { parseMoneyToCents } from "@/lib/financial-truth";
export type OutcomeActionState={status:"idle"|"success"|"error";message:string};
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const optionalInteger=(data:FormData,key:string)=>{const raw=value(data,key);if(!raw)return undefined;const parsed=Number(raw);if(!Number.isSafeInteger(parsed)||parsed<0)throw new Error(`${key} requires a nonnegative whole number.`);return parsed;};
const optionalMoney=(data:FormData,key:string)=>{const raw=value(data,key);if(!raw)return undefined;const cents=parseMoneyToCents(raw);if(cents<BigInt(0)||cents>BigInt(Number.MAX_SAFE_INTEGER))throw new Error(`${key} is outside the supported nonnegative range.`);return Number(cents);};
async function run(work:()=>Promise<unknown>,message:string):Promise<OutcomeActionState>{try{await work();revalidatePath("/executive");return{status:"success",message};}catch(error){return{status:"error",message:error instanceof Error?error.message:"Operation failed."};}}
export async function recordOutcomeAction(_state:OutcomeActionState,data:FormData){await requireOwner();return run(()=>recordTransactionOutcome({transactionId:value(data,"transactionId"),status:value(data,"status") as "CLOSED_ASSIGNED"|"CLOSED_PURCHASED"|"CANCELLED"|"FAILED",actor:"owner",sellerProceeds:optionalMoney(data,"sellerProceeds"),assignmentFee:optionalMoney(data,"assignmentFee"),transactionCosts:optionalMoney(data,"transactionCosts"),cycleDays:optionalInteger(data,"cycleDays"),reasonCode:value(data,"reasonCode") as OutcomeReasonCode,reasonExplanation:value(data,"reasonExplanation")||undefined,evidence:JSON.parse(value(data,"evidence")),decisionSnapshot:JSON.parse(value(data,"decisionSnapshot")),predictedProbabilityBps:optionalInteger(data,"predictedProbabilityBps"),projectionId:value(data,"projectionId")||undefined,priorityScoreId:value(data,"priorityScoreId")||undefined,correctionReason:value(data,"correctionReason")||undefined}),"Immutable outcome version recorded.");}
export async function createWeightProposalAction(_state:OutcomeActionState,data:FormData){await requireOwner();return run(()=>createWeightChangeProposal({minimumSampleSize:Number(value(data,"minimumSampleSize")),proposedWeights:JSON.parse(value(data,"proposedWeights")),rationale:value(data,"rationale"),sourceOutcomeIds:value(data,"sourceOutcomeIds").split(",").map(x=>x.trim()).filter(Boolean),actor:"owner"}),"Draft weight proposal recorded; no weights were applied.");}
export async function reviewWeightProposalAction(_state:OutcomeActionState,data:FormData){await requireOwner();return run(()=>reviewWeightChangeProposal({proposalId:value(data,"proposalId"),decision:value(data,"decision") as "OWNER_APPROVED"|"REJECTED",actor:"owner",reason:value(data,"reason")}),"Owner review recorded; application remains a separate manual change.");}
