"use server";
import { revalidatePath } from "next/cache";
import type { EngagementChannel, SellerAuthorityStatus, SellerDispositionReason, SellerRepresentationStatus } from "@prisma/client";
import { requireOwner } from "@/lib/auth";
import { parseMoneyToCents } from "@/lib/financial-truth";
import { createSellerEngagementDraft } from "@/lib/seller-engagement";
import { recordSellerConversation, recordSellerDisposition, recordSellerFacts, scheduleSellerFollowUp } from "@/lib/seller-crm";
const text = (data: FormData, key: string) => String(data.get(key) ?? "").trim(); const date = (data: FormData, key: string) => { const value = new Date(text(data, key)); if (Number.isNaN(value.getTime())) throw new Error(`${key} requires a date.`); return value; }; const list = (data: FormData, key: string) => text(data, key).split(",").map((item) => item.trim()).filter(Boolean); const money = (data: FormData, key: string) => text(data, key) ? parseMoneyToCents(text(data, key)) : undefined;
export async function createSellerEngagementAction(data: FormData) { await requireOwner(); await createSellerEngagementDraft({ transactionId: text(data, "transactionId"), channel: text(data, "channel") as EngagementChannel, recipient: text(data, "recipient"), recipientLabel: text(data, "recipientLabel"), purpose: text(data, "purpose"), actor: "owner" }); revalidatePath("/seller-crm"); }
export async function recordSellerConversationAction(data: FormData) { await requireOwner(); await recordSellerConversation({ engagementId: text(data, "engagementId"), occurredAt: date(data, "occurredAt"), sourceType: text(data, "sourceType"), sourceUrl: text(data, "sourceUrl") || undefined, sourceArtifactHash: text(data, "sourceArtifactHash") || undefined, summary: text(data, "summary"), objections: list(data, "objections"), questions: list(data, "questions"), actor: "owner" }); revalidatePath("/seller-crm"); }
export async function recordSellerFactsAction(data: FormData) { await requireOwner(); await recordSellerFacts({ engagementId: text(data, "engagementId"), conversationId: text(data, "conversationId"), priorities: list(data, "priorities"), timeline: text(data, "timeline") || undefined, propertyCondition: text(data, "propertyCondition") || undefined, desiredProceedsCents: money(data, "desiredProceeds"), minimumNetProceedsCents: money(data, "minimumNetProceeds"), authorityStatus: text(data, "authorityStatus") as SellerAuthorityStatus, authoritySourceUrl: text(data, "authoritySourceUrl") || undefined, representationStatus: text(data, "representationStatus") as SellerRepresentationStatus, preferredChannel: (text(data, "preferredChannel") || undefined) as EngagementChannel | undefined, independentAdviceOfferedAt: text(data, "independentAdviceOfferedAt") ? date(data, "independentAdviceOfferedAt") : undefined, sellerStatedAt: date(data, "sellerStatedAt"), correctionReason: text(data, "correctionReason") || undefined, independentAdviceRequired: data.get("independentAdviceRequired") === "on", actor: "owner" }); revalidatePath("/seller-crm"); }
export async function scheduleSellerFollowUpAction(data: FormData) { await requireOwner(); await scheduleSellerFollowUp({ engagementId: text(data, "engagementId"), dueAt: date(data, "dueAt"), reason: text(data, "reason"), channel: (text(data, "channel") || undefined) as EngagementChannel | undefined, actor: "owner" }); revalidatePath("/seller-crm"); }
export async function recordSellerDispositionAction(data: FormData) { await requireOwner(); await recordSellerDisposition({ engagementId: text(data, "engagementId"), reason: text(data, "reason") as SellerDispositionReason, explanation: text(data, "explanation") || undefined, nurtureUntil: text(data, "nurtureUntil") ? date(data, "nurtureUntil") : undefined, actor: "owner" }); revalidatePath("/seller-crm"); }
