import "server-only";

import { Prisma, type BuyerIssueStatus, type BuyerPermissionStatus, type BuyerPriceStatus, type EngagementChannel } from "@prisma/client";
import { calculateBuyerReliability, validateBuyerReliabilityWeights, validatePropertyBuyerPrice, type BuyerReliabilityInput, type BuyerReliabilityWeights } from "@/lib/buyer-reliability";
import { getPrisma } from "@/lib/prisma";

const secureUrl = (raw: string) => { const url = new URL(raw); if (url.protocol !== "https:") throw new Error("Evidence URLs must use HTTPS."); return url.toString(); };
export async function recordBuyerPropertyPrice(input: { developerId: string; demandVersionId: string; funnelId: string; status: BuyerPriceStatus; lowCents: bigint; baseCents: bigint; highCents: bigint; assumptions: string[]; sourceUrl: string; observedAt: Date; expiresAt: Date; reviewer?: string; reviewedAt?: Date }) {
  const now = new Date(); const decision = validatePropertyBuyerPrice({ ...input, now }); if (!decision.verified && ["DOCUMENTED", "COMMITTED"].includes(input.status)) throw new Error(`Buyer pricing is not verified: ${decision.blockers.join(", ")}`);
  return getPrisma().$transaction(async (tx) => { const latest = await tx.buyerPropertyPriceEvidence.findFirst({ where: { developerId: input.developerId, funnelId: input.funnelId }, orderBy: { version: "desc" } }); const record = await tx.buyerPropertyPriceEvidence.create({ data: { ...input, sourceUrl: secureUrl(input.sourceUrl), version: (latest?.version ?? 0) + 1, reviewedBy: input.reviewer, reviewedAt: input.reviewedAt } }); await tx.auditLog.create({ data: { type: "buyer.property_price.versioned", summary: `Recorded property-specific buyer price version ${record.version}.`, details: { recordId: record.id, funnelId: record.funnelId, status: record.status, blockers: decision.blockers } } }); return record; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function recordBuyerCapacity(input: { developerId: string; amountCents?: bigint; sourceUrl: string; artifactHash?: string; observedAt: Date; expiresAt: Date; reviewer: string; verified: boolean }) {
  if (input.expiresAt <= input.observedAt || input.observedAt > new Date()) throw new Error("Proof-of-funds dates are invalid."); if (input.artifactHash && !/^[a-f0-9]{64}$/i.test(input.artifactHash)) throw new Error("Artifact hash must be SHA-256.");
  return getPrisma().$transaction(async (tx) => { const latest = await tx.buyerCapacityEvidence.findFirst({ where: { developerId: input.developerId }, orderBy: { version: "desc" } }); return tx.buyerCapacityEvidence.create({ data: { developerId: input.developerId, version: (latest?.version ?? 0) + 1, status: input.verified ? "VERIFIED" : "PENDING", amountCents: input.amountCents, sourceUrl: secureUrl(input.sourceUrl), artifactHash: input.artifactHash, observedAt: input.observedAt, expiresAt: input.expiresAt, verifiedBy: input.verified ? input.reviewer : undefined, verifiedAt: input.verified ? new Date() : undefined } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function recordBuyerPermission(input: { developerId: string; channel: EngagementChannel; status: BuyerPermissionStatus; sourceUrl?: string; capturedAt: Date; expiresAt?: Date; reviewer: string }) { if (input.sourceUrl) secureUrl(input.sourceUrl); const { reviewer, ...data } = input; return getPrisma().buyerCommunicationPermission.create({ data: { ...data, reviewedBy: reviewer } }); }
export async function recordBuyerPerformanceIssue(input: { developerId: string; type: string; status: BuyerIssueStatus; occurredAt: Date; description: string; sourceUrl: string; resolution?: string; resolvedAt?: Date; reviewer: string }) { if (!input.description.trim()) throw new Error("Issue description is required."); const { reviewer, ...data } = input; return getPrisma().buyerPerformanceIssue.create({ data: { ...data, sourceUrl: secureUrl(data.sourceUrl), reviewedBy: reviewer } }); }

export async function createBuyerReliabilityConfiguration(input: { weights: BuyerReliabilityWeights; reason: string; actor: string; effectiveAt?: Date; expiresAt?: Date }) {
  validateBuyerReliabilityWeights(input.weights); if (input.reason.trim().length < 10) throw new Error("Explain why these weights were selected.");
  return getPrisma().$transaction(async (tx) => { const latest = await tx.buyerReliabilityScoreConfiguration.findFirst({ orderBy: { version: "desc" } }); return tx.buyerReliabilityScoreConfiguration.create({ data: { version: (latest?.version ?? 0) + 1, status: "DRAFT", financialCapacityWeight: input.weights.financialCapacity, marketActivityWeight: input.weights.marketActivity, criteriaSpecificityWeight: input.weights.criteriaSpecificity, responseTimeWeight: input.weights.responseTime, closingRateWeight: input.weights.closingRate, pofFreshnessWeight: input.weights.pofFreshness, retradePenaltyWeight: input.weights.retradePenalty, failedClosingPenaltyWeight: input.weights.failedClosingPenalty, unresolvedIssuePenaltyWeight: input.weights.unresolvedIssuePenalty, reason: input.reason, createdBy: input.actor, effectiveAt: input.effectiveAt, expiresAt: input.expiresAt } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function persistBuyerReliabilityScore(input: { developerId: string; demandVersionId: string; reliabilityEvidenceId: string; configurationId: string; values: BuyerReliabilityInput; actor: string; expiresAt: Date }) {
  const db = getPrisma(); const config = await db.buyerReliabilityScoreConfiguration.findUniqueOrThrow({ where: { id: input.configurationId } }); if (config.status !== "ACTIVE" || !config.effectiveAt || config.effectiveAt > input.values.now || (config.expiresAt && config.expiresAt <= input.values.now)) throw new Error("Reliability configuration is not active.");
  const weights = { financialCapacity: config.financialCapacityWeight, marketActivity: config.marketActivityWeight, criteriaSpecificity: config.criteriaSpecificityWeight, responseTime: config.responseTimeWeight, closingRate: config.closingRateWeight, pofFreshness: config.pofFreshnessWeight, retradePenalty: config.retradePenaltyWeight, failedClosingPenalty: config.failedClosingPenaltyWeight, unresolvedIssuePenalty: config.unresolvedIssuePenaltyWeight }; const score = calculateBuyerReliability(input.values, weights);
  return db.$transaction(async (tx) => { const latest = await tx.buyerReliabilityScoreHistory.findFirst({ where: { developerId: input.developerId }, orderBy: { version: "desc" } }); return tx.buyerReliabilityScoreHistory.create({ data: { developerId: input.developerId, demandVersionId: input.demandVersionId, reliabilityEvidenceId: input.reliabilityEvidenceId, configurationId: input.configurationId, version: (latest?.version ?? 0) + 1, totalScore: score.totalScore, componentScores: score.components, inputSnapshot: JSON.parse(JSON.stringify(input.values)), reasons: score.explanation, blockers: score.blockers, expiresAt: input.expiresAt, calculatedBy: input.actor } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}
