import "server-only";
import { Prisma, type CampaignCostType } from "@prisma/client";
import { getPrisma } from "@/lib/prisma";
const https = (raw: string) => { const url = new URL(raw); if (url.protocol !== "https:") throw new Error("Evidence URLs must use HTTPS."); return url.toString(); };
export async function assignCampaignOpportunity(input: { campaignId: string; funnelId: string; reason: string }) { if (input.reason.trim().length < 10) throw new Error("Assignment reason is required."); return getPrisma().campaignOpportunity.upsert({ where: { campaignId_funnelId: { campaignId: input.campaignId, funnelId: input.funnelId } }, update: { status: "INCLUDED", reason: input.reason }, create: { ...input, status: "INCLUDED" } }); }
export async function assignCampaignAgent(input: { campaignId: string; agentId: string; responsibility: string; actor: string }) { if (!input.responsibility.trim()) throw new Error("Agent responsibility is required."); return getPrisma().campaignAgentAssignment.upsert({ where: { campaignId_agentId: { campaignId: input.campaignId, agentId: input.agentId } }, update: { active: true, removedAt: null, responsibility: input.responsibility, assignedBy: input.actor }, create: { campaignId: input.campaignId, agentId: input.agentId, responsibility: input.responsibility, assignedBy: input.actor } }); }
export async function recordCampaignCost(input: { campaignId: string; funnelId?: string; type: CampaignCostType; amountCents: bigint; incurredAt: Date; sourceUrl: string; artifactHash?: string; description: string; actor: string }) { if (input.amountCents < BigInt(0) || input.incurredAt > new Date()) throw new Error("Campaign cost is invalid."); if (input.artifactHash && !/^[a-f0-9]{64}$/i.test(input.artifactHash)) throw new Error("Artifact hash must be SHA-256."); const { actor, ...data } = input; return getPrisma().campaignCostEntry.create({ data: { ...data, sourceUrl: https(data.sourceUrl), recordedBy: actor } }); }
export async function createCampaignGoalVersion(input: { campaignId: string; discoveredTarget?: number; researchedTarget?: number; sellerContactTarget?: number; offerTarget?: number; contractTarget?: number; closeTarget?: number; realizedProfitTargetCents?: bigint; effectiveAt: Date; expiresAt?: Date; actor: string }) { const values = [input.discoveredTarget,input.researchedTarget,input.sellerContactTarget,input.offerTarget,input.contractTarget,input.closeTarget]; if (values.some((value) => value != null && (!Number.isInteger(value) || value < 0))) throw new Error("Campaign goals must be nonnegative whole numbers."); return getPrisma().$transaction(async (tx) => { const latest = await tx.campaignGoalVersion.findFirst({ where: { campaignId: input.campaignId }, orderBy: { version: "desc" } }); const { actor, ...data } = input; return tx.campaignGoalVersion.create({ data: { ...data, version: (latest?.version ?? 0) + 1, createdBy: actor } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
export async function readCampaignWorkspace() {
  const db = getPrisma();
  return Promise.all([
    db.acquisitionCampaign.findMany({ include: { boundaries: { orderBy: { version: "desc" }, take: 1 }, countyCoverage: true, opportunities: { include: { funnel: { include: { property: true, transaction: { include: { settlementReviews: { orderBy: { version: "desc" }, take: 1 } } } } } } }, agentAssignments: { include: { agent: true } }, costs: true, goals: { orderBy: { version: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" } }),
    db.acquisitionFunnel.findMany({ include: { property: true }, orderBy: { updatedAt: "desc" } }),
    db.agent.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }),
  ]);
}
