import { describe, expect, it } from "vitest";
import { buildCampaignKpis, evaluateCampaignLifecycle, evaluateCampaignOpportunity } from "@/lib/campaign-economics";
describe("campaign economics", () => {
  const boundary = { allowedStates:["TX"], allowedCounties:["Hudspeth"], allowedCities:[], allowedZipCodes:[], allowedNeighborhoods:[], includedPropertyTypes:["LAND"], excludedPropertyTypes:["COMMERCIAL"], minimumRequiredProfitCents:BigInt(1_000_000), maximumEarnestMoneyCents:BigInt(100_000), maximumResearchCostCents:BigInt(50_000), maximumOutreachCostCents:BigInt(25_000), evidenceFreshnessHours:168 };
  it("requires geography, economics, freshness and county coverage together", () => expect(evaluateCampaignOpportunity({ boundary, property:{state:"TX",county:"Hudspeth",city:"Sierra Blanca",zipCode:"79851",propertyType:"LAND"}, projectedProfitCents:BigInt(2_000_000), earnestMoneyCents:BigInt(50_000), evidenceObservedAt:new Date("2026-08-18"), countyCoverageStatus:"AUTOMATED", researchCostCents:BigInt(10_000), outreachCostCents:BigInt(5_000), now:new Date("2026-08-19") }).eligible).toBe(true));
  it("blocks costs and profit outside campaign limits", () => expect(evaluateCampaignOpportunity({ boundary, property:{state:"TX",county:"Hudspeth",city:"Sierra Blanca",zipCode:"79851",propertyType:"LAND"}, projectedProfitCents:BigInt(500_000), earnestMoneyCents:BigInt(200_000), evidenceObservedAt:new Date("2026-08-18"), countyCoverageStatus:"AUTOMATED", researchCostCents:BigInt(60_000), outreachCostCents:BigInt(30_000), now:new Date("2026-08-19") }).blockers.length).toBe(4));
  it("requires owner approval, a live boundary, dates, and complete county coverage before activation", () => { const base={status:"APPROVED",ownerApprovedAt:new Date("2026-08-18"),startsAt:new Date("2026-08-01"),endsAt:new Date("2026-09-01"),boundaryCount:1,requiredCountyCount:2,coveredCountyCount:2,now:new Date("2026-08-19")}; expect(evaluateCampaignLifecycle(base).allowed).toBe(true); expect(evaluateCampaignLifecycle({...base,ownerApprovedAt:null,coveredCountyCount:1}).blockers).toEqual(["owner_approval_missing","county_coverage_incomplete"]); });
  it("reports realized profit and attributable costs separately", () => expect(buildCampaignKpis({ opportunities:[{stage:"CLOSED",realizedProfitCents:BigInt(2_000_000)}], costs:[{type:"RESEARCH",amountCents:BigInt(100_000)}], goals:{closeTarget:2,realizedProfitTargetCents:BigInt(5_000_000)} }).netAfterAttributedCostCents).toBe(BigInt(1_900_000)));
});
