import Link from "next/link";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { readOperationalReport, type OperationalReportFilters } from "@/lib/operational-report-service";
import { OutcomeControls } from "@/app/executive/outcome-controls";

export const dynamic = "force-dynamic";
const field = "rounded-lg border px-3 py-2 text-sm";
const reportSections = [
  { title: "Money", description: "What the pipeline may produce versus money actually closed.", keys: ["projected_pipeline", "weighted_pipeline", "contracted_pipeline", "realized_profit", "average_closed_profit", "cost_per_closed_transaction"] },
  { title: "Deal progress", description: "How opportunities are moving from discovery to a completed transaction.", keys: ["properties_discovered", "properties_researched", "outreach_ready", "sellers_reached", "qualified_conversations", "offers_prepared", "offers_approved", "offers_delivered", "contracts_signed", "deals_closed"] },
  { title: "Speed", description: "How long research, contact, and deal stages are taking.", keys: ["research_completion_rate", "discovery_to_contact_hours", "average_stage_hours", "median_stage_hours"] },
  { title: "Attention needed", description: "Evidence, approval, buyer, and agent issues that may slow results.", keys: ["manual_verification_backlog", "research_exception_rate", "evidence_freshness", "owner_approval_queue_age", "buyer_closing_rate", "buyer_retrade_rate", "agent_queue_failures", "agent_retry_count"] },
] as const;
function display(value: number | string | null, unit: string) {
  if (value == null) return "Not enough data";
  if (unit === "cents") return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value) / 100);
  return unit === "percent" ? `${value}%` : unit === "hours" ? `${value} hours` : String(value);
}

export default async function ExecutivePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireOwner();
  const raw = await searchParams;
  const filters: OperationalReportFilters = Object.fromEntries(Object.entries(raw).flatMap(([key, value]) => typeof value === "string" && value ? [[key, value]] : []));
  const report = await readOperationalReport(filters);
  const query = new URLSearchParams(Object.entries(filters).flatMap(([key, value]) => value ? [[key, value]] : [])).toString();
  return <WorkspaceShell active="executive"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><p className="text-sm font-semibold text-blue-700">Business results</p><h1 className="mt-1 text-3xl font-bold">Profit & reports</h1><p className="mt-2 text-sm text-slate-600">Start with money and deal progress. Open the detailed sections only when you need them.</p></div><Link className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white" href={`/api/exports/executive${query ? `?${query}` : ""}`}>Download report</Link></header>
    <details className="mt-6 rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">Filter this report</summary><form className="mt-4 grid gap-3 md:grid-cols-4 xl:grid-cols-6">{[["start","date","Start"],["end","date","End"],["state","text","State"],["county","text","County"],["zip","text","ZIP"],["stage","text","Deal stage"],["buyerId","text","Buyer"],["agentId","text","Agent"],["propertyType","text","Property type"],["leadSource","text","Lead source"],["transactionStructure","text","Deal structure"]].map(([name,type,placeholder])=><input className={field} defaultValue={filters[name as keyof OperationalReportFilters]} key={name} name={name} placeholder={placeholder} type={type}/>) }<button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Update report</button></form></details>
    {reportSections.map((section, sectionIndex) => { const metrics = report.metrics.filter((metric) => (section.keys as readonly string[]).includes(metric.key)); return metrics.length ? <section className="mt-6" key={section.title}><div><h2 className="text-xl font-bold">{section.title}</h2><p className="mt-1 text-sm text-slate-500">{section.description}</p></div><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <article className="rounded-2xl border bg-white p-5" key={metric.key}><p className="text-sm font-semibold text-slate-600">{metric.label}</p><p className="mt-2 text-2xl font-bold">{display(metric.value, metric.unit)}</p>{sectionIndex > 1 ? <p className="mt-3 text-xs leading-5 text-slate-600">{metric.definition}</p> : null}{metric.warning ? <p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800">{metric.warning}</p> : null}<details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer font-semibold">How this is calculated</summary><p className="mt-2">{metric.definition}</p><p className="mt-1">Sample: {metric.sampleSize} · Refreshed {new Date(metric.lastRefresh).toLocaleString()}</p></details></article>)}</div></section> : null; })}
    <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Fallout reasons</h2><div className="mt-3 flex flex-wrap gap-2">{Object.entries(report.falloutReasons).length ? Object.entries(report.falloutReasons).map(([reason, count]) => <span className="rounded-full bg-slate-100 px-3 py-1 text-sm" key={reason}>{reason}: {count}</span>) : <p className="text-sm text-slate-500">No finalized fallout evidence in this window.</p>}</div></section>
    <details className="mt-6 rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">Profit by market, buyer, and source</summary><p className="mt-2 text-sm text-slate-500">Projected and closed profit remain separate.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{Object.entries(report.profitSegments).map(([dimension, rows])=><div className="overflow-hidden rounded-xl border" key={dimension}><h3 className="bg-slate-50 px-3 py-2 text-sm font-bold capitalize">{dimension}</h3><table className="w-full text-left text-xs"><thead><tr><th className="px-3 py-2">Segment</th><th className="px-3 py-2">Projected</th><th className="px-3 py-2">Realized</th><th className="px-3 py-2">Deals</th></tr></thead><tbody>{rows.map((row)=><tr className="border-t" key={row.key}><td className="px-3 py-2">{row.key}</td><td className="px-3 py-2">{display(row.projectedCents,"cents")}</td><td className="px-3 py-2">{display(row.realizedCents,"cents")}</td><td className="px-3 py-2">{row.dealCount} / {row.realizedCount} closed</td></tr>)}</tbody></table></div>)}</div></details>
    <details className="mt-6 rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">Forecast accuracy</summary><p className="mt-2 text-sm text-slate-500">This advanced view compares prior predictions with finalized outcomes.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th>Dimension</th><th>Segment</th><th>Final</th><th>Financial pairs</th><th>Financial MAE</th><th>Probability pairs</th><th>Probability MAE</th></tr></thead><tbody>{report.forecastErrors.map((row)=><tr className="border-t" key={`${row.dimension}:${row.key}`}><td className="py-2">{row.dimension}</td><td>{row.key}</td><td>{row.finalizedSampleSize}</td><td>{row.financialPairedSampleSize}</td><td>{row.meanAbsoluteFinancialError==null?"Not enough data":display(row.meanAbsoluteFinancialError,"cents")}</td><td>{row.probabilityPairedSampleSize}</td><td>{row.meanAbsoluteProbabilityErrorBps==null?"Not enough data":`${row.meanAbsoluteProbabilityErrorBps} bps`}</td></tr>)}</tbody></table></div></details>
    <details className="mt-6 rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">Record final outcomes and model reviews</summary><div className="mt-4"><OutcomeControls /></div></details>
  </div></WorkspaceShell>;
}
