import { createPropertyAction, importPropertiesCsvAction } from "@/app/actions";
import { CsvImportForm } from "@/app/csv-import-form";
import { PropertyBrowser, type PropertyView } from "@/app/properties/property-browser";
import { WorkspaceShell } from "@/app/workspace-shell";
import { requireOwner } from "@/lib/auth";
import { readDatabase, scoreDeveloperMatches } from "@/lib/database";

export const dynamic = "force-dynamic";
function Field({ name, placeholder, type = "text", required = false }: { name: string; placeholder: string; type?: string; required?: boolean }) { return <input className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" name={name} placeholder={placeholder} type={type} required={required} />; }

export default async function PropertiesPage() {
  await requireOwner(); const db = await readDatabase(); const developerById = new Map(db.developers.map((d) => [d.id, d]));
  const properties: PropertyView[] = await Promise.all(db.properties.map(async (property) => ({ ...property, matches: (await scoreDeveloperMatches(property.id, false)).slice(0, 5).map((match) => ({ ...match, companyName: developerById.get(match.developerId)?.companyName ?? "Unknown developer" })) })));
  return <WorkspaceShell><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8"><header className="flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Acquisition pipeline</p><h1 className="mt-1 text-3xl font-bold">Properties</h1><p className="mt-2 text-sm text-slate-600">Review candidates visually and compare developer matches.</p></div><div className="flex gap-2"><a className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold" href="#import-properties">Import CSV</a><a className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white" href="#add-property">Add property</a></div></header><div className="mt-6"><PropertyBrowser properties={properties} /></div><section className="mt-8 grid gap-6 xl:grid-cols-2"><details className="rounded-2xl border bg-white p-5 shadow-sm" id="import-properties"><summary className="cursor-pointer font-bold">Import properties from CSV</summary><div className="mt-4"><CsvImportForm action={importPropertiesCsvAction} buttonLabel="Import properties" helpText="Required: Address, City, two-letter State, and ZIP. Optional: Owner Name, Year Built, Lot Size, Estimated Value, Zoning, Utilities, Source, and Notes." /></div></details><details className="rounded-2xl border bg-white p-5 shadow-sm" id="add-property"><summary className="cursor-pointer font-bold">Add one property manually</summary><form action={createPropertyAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="address" placeholder="Street address" required /><Field name="ownerName" placeholder="Owner or listing contact" required /><Field name="city" placeholder="City" required /><Field name="state" placeholder="State" required /><Field name="zipCode" placeholder="ZIP" required /><Field name="estimatedValue" placeholder="Asking or estimated value" type="number" required /><Field name="lotSize" placeholder="Lot size or acreage" /><Field name="yearBuilt" placeholder="Year built" /><textarea className="min-h-24 rounded-xl border p-3 text-sm sm:col-span-2" name="notes" placeholder="Zoning, utilities, frontage, source, and research notes" /><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white sm:col-span-2">Save property candidate</button></form></details></section></div></WorkspaceShell>;
}
