"use client";

import { useMemo, useState } from "react";

export type PropertyView = {
  id: string; address: string; city: string; state: string; zipCode: string; ownerName: string; yearBuilt?: string; lotSize?: string; estimatedValue?: number; notes?: string;
  opportunityStatus: "NEEDS_VERIFICATION" | "DEVELOPMENT_SIGNAL" | "CONFIRMED_AVAILABLE" | "GOVERNMENT_SALE" | "REJECTED";
  contactName?: string; contactPhone?: string; contactEmail?: string; sourceName?: string; sourceUrl?: string; sourceRecordDate?: string; lastVerifiedAt?: string; confidence: number;
  matches: Array<{ developerId: string; companyName: string; score: number; reasons: string[] }>;
};
const money = (value?: number) => value ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value) : "Value unknown";
const labels = { NEEDS_VERIFICATION: "Needs verification", DEVELOPMENT_SIGNAL: "Development signal", CONFIRMED_AVAILABLE: "Confirmed available", GOVERNMENT_SALE: "Government sale", REJECTED: "Rejected" };
const actionable = (property: PropertyView) => ["CONFIRMED_AVAILABLE", "GOVERNMENT_SALE"].includes(property.opportunityStatus) && Boolean(property.sourceUrl) && Boolean(property.contactPhone || property.contactEmail);

export function PropertyBrowser({ properties }: { properties: PropertyView[] }) {
  const [query, setQuery] = useState("");
  const [view, setView] = useState<"actionable" | "research">("actionable");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => properties.filter((property) => (view === "actionable" ? actionable(property) : !actionable(property)) && [property.address, property.city, property.state, property.zipCode, property.ownerName, property.contactName, property.sourceName].filter(Boolean).some((value) => value?.toLowerCase().includes(query.toLowerCase()))), [properties, query, view]);
  const selected = properties.find((property) => property.id === selectedId);
  const actionableCount = properties.filter(actionable).length;

  return <>
    <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><input className="min-w-0 flex-1 rounded-xl border bg-slate-50 px-4 py-2.5 text-sm" onChange={(event) => setQuery(event.target.value)} placeholder="Search address, city, contact, source…" value={query} /><div className="flex rounded-xl border p-1"><button className={`rounded-lg px-3 py-1.5 text-sm font-semibold ${view === "actionable" ? "bg-slate-950 text-white" : "text-slate-500"}`} onClick={() => setView("actionable")}>Actionable · {actionableCount}</button><button className={`rounded-lg px-3 py-1.5 text-sm font-semibold ${view === "research" ? "bg-amber-600 text-white" : "text-slate-500"}`} onClick={() => setView("research")}>Needs verification · {properties.length - actionableCount}</button></div></div></div>
    <div className="mt-5 grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{filtered.map((property, index) => <button className="overflow-hidden rounded-2xl border bg-white text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" key={property.id} onClick={() => setSelectedId(property.id)}><div className={`relative grid min-h-40 place-items-center bg-gradient-to-br ${index % 3 === 0 ? "from-blue-100 to-slate-200" : index % 3 === 1 ? "from-amber-100 to-orange-100" : "from-emerald-100 to-slate-200"}`}><span className="text-5xl opacity-60">⌂</span><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-1 text-xs font-bold">{labels[property.opportunityStatus]}</span></div><div className="p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{property.address}</h2><p className="mt-1 text-sm text-slate-500">{property.city}, {property.state} {property.zipCode}</p></div><span className="h-fit rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-800">{property.matches.length} matches</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg bg-slate-50 p-2"><span className="block text-slate-500">Value</span><b>{money(property.estimatedValue)}</b></span><span className="rounded-lg bg-slate-50 p-2"><span className="block text-slate-500">Confidence</span><b>{property.confidence}%</b></span></div><p className="mt-4 text-sm font-semibold text-blue-700">Open evidence →</p></div></button>)}</div>
    {!filtered.length ? <p className="mt-5 rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">{view === "actionable" ? "No properties meet the actionable standard yet." : "No properties need verification."}</p> : null}
    {selected ? <div className="fixed inset-0 z-50 bg-slate-950/40 p-3 sm:p-6" onClick={() => setSelectedId(null)}><aside aria-modal="true" className="ml-auto h-full max-w-xl overflow-y-auto rounded-2xl bg-white shadow-2xl" onClick={(event) => event.stopPropagation()} role="dialog"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Property evidence</p><h2 className="mt-1 text-xl font-bold">{selected.address}</h2></div><button aria-label="Close" className="grid h-10 w-10 place-items-center rounded-full bg-slate-100 text-xl" onClick={() => setSelectedId(null)}>×</button></div><div className="p-5"><dl className="grid grid-cols-2 gap-4 text-sm">{[["Location", `${selected.city}, ${selected.state} ${selected.zipCode}`], ["Owner", selected.ownerName], ["Status", labels[selected.opportunityStatus]], ["Confidence", `${selected.confidence}%`], ["Contact", selected.contactName || "Missing"], ["Phone", selected.contactPhone || "Missing"], ["Email", selected.contactEmail || "Missing"], ["Record date", selected.sourceRecordDate || "Missing"]].map(([label, value]) => <div key={label}><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>)}</dl><section className="mt-7 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Government source</h3>{selected.sourceUrl ? <a className="mt-2 inline-block text-sm font-bold text-blue-700 underline" href={selected.sourceUrl} rel="noreferrer" target="_blank">Open {selected.sourceName || "official record"}</a> : <p className="mt-2 text-sm text-red-700">No source URL recorded.</p>}</section><section className="mt-7"><h3 className="font-bold">Developer matches</h3><div className="mt-3 space-y-3">{selected.matches.map((match) => <article className="rounded-xl border p-4" key={match.developerId}><div className="flex justify-between"><b>{match.companyName}</b><b className="text-blue-700">{match.score}</b></div><p className="mt-2 text-xs leading-5 text-slate-500">{match.reasons.join(" ")}</p></article>)}{!selected.matches.length ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Matching stays locked until the opportunity and developer both qualify.</p> : null}</div></section></div></aside></div> : null}
  </>;
}
