"use client";

import { useMemo, useState } from "react";

export type PropertyView = { id: string; address: string; city: string; state: string; zipCode: string; ownerName: string; yearBuilt?: string; lotSize?: string; estimatedValue?: number; notes?: string; matches: Array<{ developerId: string; companyName: string; score: number; reasons: string[] }> };
const money = (value?: number) => typeof value === "number" && value > 0 ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value) : "Value unknown";

export function PropertyBrowser({ properties }: { properties: PropertyView[] }) {
  const [query, setQuery] = useState(""); const [view, setView] = useState<"grid" | "list">("grid"); const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => properties.filter((p) => [p.address, p.city, p.state, p.zipCode, p.ownerName].some((value) => value.toLowerCase().includes(query.toLowerCase()))), [properties, query]);
  const selected = properties.find((p) => p.id === selectedId);
  return <><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row"><input className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-slate-50 px-4 py-2.5 text-sm" onChange={(e) => setQuery(e.target.value)} placeholder="Search address, city, owner, or ZIP…" value={query} /><div className="flex rounded-xl border border-slate-300 p-1"><button className={`rounded-lg px-3 py-1.5 text-sm font-semibold ${view === "grid" ? "bg-slate-950 text-white" : "text-slate-500"}`} onClick={() => setView("grid")}>Grid</button><button className={`rounded-lg px-3 py-1.5 text-sm font-semibold ${view === "list" ? "bg-slate-950 text-white" : "text-slate-500"}`} onClick={() => setView("list")}>List</button></div></div>
    <div className={`mt-5 grid gap-5 ${view === "grid" ? "md:grid-cols-2 2xl:grid-cols-3" : "grid-cols-1"}`}>{filtered.map((p, i) => <button className={`overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${view === "list" ? "sm:grid sm:grid-cols-[220px_1fr]" : ""}`} key={p.id} onClick={() => setSelectedId(p.id)}><div className={`relative grid min-h-40 place-items-center bg-gradient-to-br ${i % 3 === 0 ? "from-blue-100 to-slate-200" : i % 3 === 1 ? "from-amber-100 to-orange-100" : "from-emerald-100 to-slate-200"}`}><span className="text-5xl opacity-60">⌂</span><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-1 text-xs font-bold">Research</span></div><div className="p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{p.address}</h2><p className="mt-1 text-sm text-slate-500">{p.city}, {p.state} {p.zipCode}</p></div><span className="h-fit rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-800">{p.matches.length} matches</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg bg-slate-50 p-2"><span className="block text-slate-500">Value</span><b className="mt-1 block">{money(p.estimatedValue)}</b></span><span className="rounded-lg bg-slate-50 p-2"><span className="block text-slate-500">Lot</span><b className="mt-1 block">{p.lotSize || "Unknown"}</b></span></div><p className="mt-4 text-sm font-semibold text-blue-700">Open property details →</p></div></button>)}</div>
    {!filtered.length ? <p className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No properties match this search.</p> : null}
    {selected ? <div className="fixed inset-0 z-50 bg-slate-950/40 p-3 sm:p-6" onClick={() => setSelectedId(null)}><aside aria-modal="true" className="ml-auto h-full max-w-xl overflow-y-auto rounded-2xl bg-white shadow-2xl" onClick={(e) => e.stopPropagation()} role="dialog"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Property details</p><h2 className="mt-1 text-xl font-bold">{selected.address}</h2></div><button aria-label="Close" className="grid h-10 w-10 place-items-center rounded-full bg-slate-100 text-xl" onClick={() => setSelectedId(null)}>×</button></div><div className="p-5"><div className="grid min-h-52 place-items-center rounded-2xl bg-gradient-to-br from-blue-100 to-slate-200 text-7xl">⌂</div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm">{[["Location", `${selected.city}, ${selected.state} ${selected.zipCode}`], ["Owner", selected.ownerName], ["Estimated value", money(selected.estimatedValue)], ["Lot size", selected.lotSize || "Unknown"], ["Year built", selected.yearBuilt || "Unknown"], ["Status", "Research"]].map(([label, value]) => <div key={label}><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>)}</dl><section className="mt-7"><h3 className="font-bold">Research notes</h3><p className="mt-2 whitespace-pre-line rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{selected.notes || "No research notes recorded."}</p></section><section className="mt-7"><h3 className="font-bold">Developer matches</h3><div className="mt-3 space-y-3">{selected.matches.map((m) => <article className="rounded-xl border p-4" key={m.developerId}><div className="flex justify-between"><b>{m.companyName}</b><b className="text-blue-700">{m.score}</b></div><p className="mt-2 text-xs leading-5 text-slate-500">{m.reasons.join(" ")}</p></article>)}{!selected.matches.length ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No developer matches yet.</p> : null}</div></section></div></aside></div> : null}</>;
}
